(() => {
  const repository = window.northstarRepository;
  if (!repository || document.querySelector('#material-dialog')) return;
  const dialog = document.createElement('dialog'); dialog.id = 'material-dialog'; dialog.className = 'workflow-dialog';
  dialog.innerHTML = '<button class="dialog-close" type="button" data-close-material aria-label="Close">×</button><div class="dialog-kicker">INVENTORY</div><h2 id="material-title">Add inventory item</h2><p id="material-help">Create a material with stock, cost, and replenishment controls for this service workspace.</p><form><label>Material name<input name="name" maxlength="120" required placeholder="PVC coupling, detergent, filter…" /></label><label>SKU<input name="sku" maxlength="80" required placeholder="SKU-001" /></label><label>Barcode <span>(optional)</span><input name="barcode" maxlength="120" inputmode="numeric" /></label><label>Unit<input name="unit" maxlength="30" required value="each" /></label><label>Unit cost<input name="unitCost" type="number" min="0" step="0.01" required value="0" /></label><label>Quantity on hand<input name="onHand" type="number" min="0" step="1" required value="0" /></label><label>Reorder point<input name="reorderPoint" type="number" min="0" step="1" required value="2" /></label><div class="workflow-actions"><button class="ghost-btn" type="button" data-close-material>Cancel</button><button class="primary-btn" type="submit">Save inventory item</button></div><p class="form-message" data-material-status role="status" aria-live="polite"></p></form>';
  document.body.append(dialog); dialog.setAttribute('aria-labelledby', 'material-title'); dialog.setAttribute('aria-describedby', 'material-help');
  const form = dialog.querySelector('form'); const status = dialog.querySelector('[data-material-status]'); const submit = form.querySelector('[type="submit"]');
  dialog.querySelectorAll('[data-close-material]').forEach((button) => button.addEventListener('click', () => dialog.close()));
  const open = () => { form.reset(); form.elements.unit.value = 'each'; form.elements.unitCost.value = '0'; form.elements.onHand.value = '0'; form.elements.reorderPoint.value = '2'; status.textContent = ''; submit.disabled = false; dialog.showModal(); form.elements.name.focus(); };
  form.addEventListener('submit', async (event) => { event.preventDefault(); if (!form.reportValidity()) return; const values = Object.fromEntries(new FormData(form).entries()); const unitCost = Number(values.unitCost); const onHand = Number(values.onHand); const reorderPoint = Number(values.reorderPoint); if (!values.name.trim() || !values.sku.trim() || !values.unit.trim() || !Number.isFinite(unitCost) || unitCost < 0 || !Number.isInteger(onHand) || onHand < 0 || !Number.isInteger(reorderPoint) || reorderPoint < 0) { status.textContent = 'Enter a name, SKU, unit, non-negative cost, and whole-number stock values.'; return; } submit.disabled = true; status.textContent = 'Saving inventory item…'; try { const material = await repository.createMaterial(values.name.trim(), values.sku.trim(), values.unit.trim(), unitCost, onHand, reorderPoint); if (values.barcode.trim()) await repository.setMaterialBarcode(material.id, values.barcode.trim()); dialog.close(); showToast('Inventory item added.'); openRecords('materials'); } catch { status.textContent = 'Could not add inventory item. Check the SKU, barcode, and stock values.'; submit.disabled = false; } });
  document.addEventListener('click', (event) => { const button = event.target.closest('#add-material'); if (!button) return; event.preventDefault(); event.stopImmediatePropagation(); open(); }, true);
})();
