import { createHmac, timingSafeEqual } from 'node:crypto';
import { createReadStream, existsSync, readFileSync, renameSync, statSync, writeFileSync } from 'node:fs';
import { extname, join, normalize, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'node:http';

const ROOT = fileURLToPath(new URL('.', import.meta.url)).replace(/[\\/]$/, '');
const PORT = Number(process.env.PORT || 4173);
const SECRET = process.env.NORTHSTAR_SESSION_SECRET || 'northstar-local-demo-secret-change-me';
const DATA_FILE = process.env.NORTHSTAR_DATA_FILE || join(ROOT, '.northstar-data.json');
const ALLOWED_ORIGINS = new Set(String(process.env.NORTHSTAR_ALLOWED_ORIGINS || '').split(',').map((origin) => origin.trim()).filter(Boolean));
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.md': 'text/markdown; charset=utf-8' };

const tenants = {
  'johnson-service-co': { slug: 'johnson-service-co', businessName: 'Johnson Service Co.', serviceLabel: 'Home services' },
  'clearwater-plumbing': { slug: 'clearwater-plumbing', businessName: 'Clearwater Plumbing', serviceLabel: 'Plumbing' },
  'lowcountry-wash-co': { slug: 'lowcountry-wash-co', businessName: 'Lowcountry Wash Co.', serviceLabel: 'Power washing' },
  'palmetto-electric': { slug: 'palmetto-electric', businessName: 'Palmetto Electric', serviceLabel: 'Electrical' },
  'harbor-shine': { slug: 'harbor-shine', businessName: 'Harbor Shine Mobile', serviceLabel: 'Mobile car wash' }
};
const owners = { jordan: { id: 'owner_jordan', name: 'Jordan Smith', role: 'owner', tenantId: 'johnson-service-co' } };
const rolePermissions = { owner: ['dashboard:read', 'records:read', 'reports:read', 'customers:write', 'leads:write', 'jobs:write', 'estimates:write', 'invoices:write', 'payments:write', 'inventory:write', 'tasks:write', 'activities:write', 'exports:read'], dispatcher: ['dashboard:read', 'records:read', 'reports:read', 'customers:write', 'leads:write', 'jobs:write', 'estimates:write', 'inventory:write', 'tasks:write', 'activities:write', 'exports:read'], technician: ['dashboard:read', 'records:read', 'jobs:write', 'inventory:write', 'activities:write'], accountant: ['dashboard:read', 'records:read', 'reports:read', 'invoices:write', 'payments:write', 'exports:read'] };
const demoStaff = { owner: owners.jordan, dispatcher: { id: 'staff_dispatcher', name: 'Taylor Brooks', role: 'dispatcher' }, technician: { id: 'staff_technician', name: 'Alex Rivera', role: 'technician' }, accountant: { id: 'staff_accountant', name: 'Morgan Lee', role: 'accountant' } };
const serviceTenant = { default: 'johnson-service-co', plumbing: 'clearwater-plumbing', powerwashing: 'lowcountry-wash-co', electrician: 'palmetto-electric', carwash: 'harbor-shine' };
const teamFor = (tenantId) => { const active = state.get(tenantId).jobs.filter((item) => item.technician && !['Completed', 'Canceled'].includes(item.status)); return [{ id: `${tenantId}_tech_1`, name: 'Alex Rivera', role: 'Lead technician' }, { id: `${tenantId}_tech_2`, name: 'Marcus Thompson', role: 'Field technician' }, { id: `${tenantId}_tech_3`, name: 'Priya Shah', role: 'Field technician' }].map((member) => { const jobs = active.filter((item) => item.technician === member.name); return { ...member, status: jobs.length ? 'On job' : 'Available', activeJobs: jobs.length }; }); };
const catalogFor = (tenantId) => { const label = tenants[tenantId].serviceLabel; return [{ id: `${tenantId}_service_1`, name: `${label} inspection`, description: 'Diagnostic visit and written recommendations', priceFrom: '$149' }, { id: `${tenantId}_service_2`, name: `${label} repair`, description: 'Standard repair visit with parts billed separately', priceFrom: '$289' }, { id: `${tenantId}_service_3`, name: `${label} maintenance plan`, description: 'Recurring service with priority scheduling', priceFrom: '$89 / month' }, { id: `${tenantId}_service_4`, name: `${label} installation`, description: 'On-site installation and commissioning', priceFrom: '$680' }]; };
const defaultChecklist = () => [{ label: 'Arrived on site', completed: false }, { label: 'Work performed and documented', completed: false }, { label: 'Customer handoff completed', completed: false }];
const notificationsFor = (tenantId) => { const saved = state.get(tenantId); const notifications = []; const add = (item) => notifications.push({ ...item, read: saved.notificationReads.includes(item.id) }); saved.leads.filter((item) => item.status !== 'Converted').forEach((item) => add({ id: `N-${item.id}`, title: 'New lead needs follow-up', detail: `${item.name} · ${item.service}`, status: 'Action needed' })); saved.requests.filter((item) => item.status === 'Open').forEach((item) => add({ id: `N-${item.id}`, title: 'Customer request needs response', detail: `${item.customer} · ${item.type}`, status: 'Action needed' })); saved.jobs.filter((item) => item.status === 'Unassigned').forEach((item) => add({ id: `N-${item.id}`, title: 'Unassigned job', detail: `${item.service} · ${item.time}`, status: 'Action needed' })); saved.invoices.filter((item) => item.status !== 'Paid').forEach((item) => add({ id: `N-${item.id}`, title: 'Invoice needs attention', detail: `${item.customer} · ${item.value}`, status: 'Review' })); saved.plans.filter((item) => item.status === 'Renewing soon').forEach((item) => add({ id: `N-${item.id}`, title: 'Plan renewal approaching', detail: `${item.customer} · ${item.renewal}`, status: 'Follow up' })); return notifications; };
const blankState = () => ({ completedTasks: [], lastAction: null, leads: [], jobs: [], estimates: [], invoices: [], payments: [], paymentIntents: [], plans: [], activities: [], customers: [], assets: [], locations: [], reviews: [], requests: [], materials: [], inventoryTransactions: [], purchaseOrders: [], laborEntries: [], messages: [], notificationReads: [] });
const persisted = existsSync(DATA_FILE) ? JSON.parse(readFileSync(DATA_FILE, 'utf8')) : {};
const state = new Map(Object.keys(tenants).map((tenantId) => [tenantId, { ...blankState(), ...(persisted[tenantId] || {}) }]));
const publicLeadWindows = new Map();
const revokedTokens = new Set();
const persist = () => { const snapshot = Object.fromEntries(state); writeFileSync(`${DATA_FILE}.tmp`, JSON.stringify(snapshot, null, 2)); renameSync(`${DATA_FILE}.tmp`, DATA_FILE); };
const recordActivity = (saved, customer, channel, note, status = 'Logged') => { saved.activities.unshift({ id: `ACT-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, customer: String(customer).slice(0, 100), channel, note: String(note).slice(0, 500), at: 'Just now', status }); };

const json = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' }); res.end(JSON.stringify(body)); };
const readBody = async (req) => { let body = ''; for await (const chunk of req) { body += chunk; if (Buffer.byteLength(body, 'utf8') > 64 * 1024) throw new Error('request_body_too_large'); } return body ? JSON.parse(body) : {}; };
const allowPublicLead = (req) => { const key = req.socket.remoteAddress || 'unknown'; const now = Date.now(); const window = publicLeadWindows.get(key); if (!window || now - window.startedAt >= 60_000) { publicLeadWindows.set(key, { startedAt: now, count: 1 }); return true; } if (window.count >= 20) return false; window.count += 1; return true; };
const sign = (value) => createHmac('sha256', SECRET).update(value).digest('base64url');
const issueToken = (owner) => { const payload = Buffer.from(JSON.stringify({ sub: owner.id, tenantId: owner.tenantId, role: owner.role, exp: Date.now() + 1000 * 60 * 60 * 8 })).toString('base64url'); return `${payload}.${sign(payload)}`; };
const issueJobStatusToken = (job) => { const payload = Buffer.from(JSON.stringify({ jobId: job.id, tenantId: job.tenantId, exp: Date.now() + 1000 * 60 * 60 * 72 })).toString('base64url'); return `${payload}.${sign(payload)}`; };
const readJobStatusToken = (token) => { const [payload, signature] = String(token || '').split('.'); if (!payload || !signature) return null; const expected = sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const claims = JSON.parse(Buffer.from(payload, 'base64url')); return claims.exp > Date.now() && tenants[claims.tenantId] ? claims : null; } catch { return null; } };
const issueEstimateToken = (estimate) => { const payload = Buffer.from(JSON.stringify({ estimateId: estimate.id, tenantId: estimate.tenantId, exp: Date.now() + 1000 * 60 * 60 * 72 })).toString('base64url'); return `${payload}.${sign(payload)}`; };
const readEstimateToken = (token) => { const [payload, signature] = String(token || '').split('.'); if (!payload || !signature) return null; const expected = sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const claims = JSON.parse(Buffer.from(payload, 'base64url')); return claims.exp > Date.now() && tenants[claims.tenantId] ? claims : null; } catch { return null; } };
const issueTechnicianToken = (job) => { const payload = Buffer.from(JSON.stringify({ scope: 'technician', jobId: job.id, tenantId: job.tenantId, technician: job.technician, exp: Date.now() + 1000 * 60 * 60 * 24 })).toString('base64url'); return `${payload}.${sign(payload)}`; };
const readTechnicianToken = (token) => { const [payload, signature] = String(token || '').split('.'); if (!payload || !signature) return null; const expected = sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const claims = JSON.parse(Buffer.from(payload, 'base64url')); return claims.scope === 'technician' && claims.exp > Date.now() && tenants[claims.tenantId] ? claims : null; } catch { return null; } };
const issueCustomerToken = (tenantId, customerId) => { const payload = Buffer.from(JSON.stringify({ scope: 'customer', customerId, tenantId, exp: Date.now() + 1000 * 60 * 60 * 72 })).toString('base64url'); return `${payload}.${sign(payload)}`; };
const readCustomerToken = (token) => { const [payload, signature] = String(token || '').split('.'); if (!payload || !signature) return null; const expected = sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const claims = JSON.parse(Buffer.from(payload, 'base64url')); return claims.scope === 'customer' && claims.exp > Date.now() && tenants[claims.tenantId] ? claims : null; } catch { return null; } };
const issueReviewToken = (job) => { const payload = Buffer.from(JSON.stringify({ scope: 'review', jobId: job.id, tenantId: job.tenantId, exp: Date.now() + 1000 * 60 * 60 * 72 })).toString('base64url'); return `${payload}.${sign(payload)}`; };
const readReviewToken = (token) => { const [payload, signature] = String(token || '').split('.'); if (!payload || !signature) return null; const expected = sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const claims = JSON.parse(Buffer.from(payload, 'base64url')); return claims.scope === 'review' && claims.exp > Date.now() && tenants[claims.tenantId] ? claims : null; } catch { return null; } };
const issueInvoiceToken = (invoice) => { const payload = Buffer.from(JSON.stringify({ scope: 'invoice', invoiceId: invoice.id, tenantId: invoice.tenantId, exp: Date.now() + 1000 * 60 * 60 * 72 })).toString('base64url'); return `${payload}.${sign(payload)}`; };
const readInvoiceToken = (token) => { const [payload, signature] = String(token || '').split('.'); if (!payload || !signature) return null; const expected = sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const claims = JSON.parse(Buffer.from(payload, 'base64url')); return claims.scope === 'invoice' && claims.exp > Date.now() && tenants[claims.tenantId] ? claims : null; } catch { return null; } };
const authenticate = (req) => {
  const raw = req.headers.authorization || '';
  const token = raw.startsWith('Bearer ') ? raw.slice(7) : '';
  if (revokedTokens.has(token)) return null;
  const [payload, signature] = token.split('.');
  if (!payload || !signature) return null;
  const expected = sign(payload);
  if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null;
  try { const claims = JSON.parse(Buffer.from(payload, 'base64url')); return claims.exp > Date.now() && demoStaff[claims.role]?.id === claims.sub && tenants[claims.tenantId] ? claims : null; } catch { return null; }
};
const permissionFor = (pathname, method) => { if (method === 'GET' && pathname === '/api/dashboard') return 'dashboard:read'; if (method === 'GET' && pathname === '/api/reports/overview') return 'reports:read'; if (method === 'GET' && pathname === '/api/export') return 'exports:read'; if (method === 'GET' && /^\/api\/(customers|leads|estimates|invoices|payments|plans|activities|dispatch|team|catalog|notifications|assets|reviews|requests|materials|purchase-orders|job-costs|messages)$/.test(pathname)) return 'records:read'; if (pathname === '/api/invoices' || /^\/api\/invoices\/[^/]+\/pay$/.test(pathname)) return method === 'GET' ? 'records:read' : 'invoices:write'; if (pathname === '/api/payments') return 'records:read'; if (pathname === '/api/tasks' || /^\/api\/tasks\//.test(pathname)) return 'tasks:write'; if (pathname === '/api/actions') return 'activities:write'; if (pathname === '/api/customers' || /^\/api\/customers\/[^/]+\/locations$/.test(pathname) || pathname === '/api/assets') return 'customers:write'; if (pathname === '/api/leads' || /^\/api\/leads\//.test(pathname)) return 'leads:write'; if (pathname === '/api/estimates' || /^\/api\/estimates\//.test(pathname)) return 'estimates:write'; if (pathname === '/api/jobs' || /^\/api\/jobs\//.test(pathname) || pathname === '/api/plans' || /^\/api\/plans\//.test(pathname)) return 'jobs:write'; if (pathname === '/api/activities' || pathname === '/api/messages') return 'activities:write'; if (pathname === '/api/materials' || /^\/api\/jobs\/[^/]+\/materials$/.test(pathname) || pathname === '/api/purchase-orders' || /^\/api\/purchase-orders\//.test(pathname)) return method === 'GET' ? 'records:read' : 'inventory:write'; return null; };
const allowed = (claims, permission) => !permission || rolePermissions[claims.role]?.includes(permission);
const dashboardFor = (tenantId) => {
  const base = { 'johnson-service-co': ['$84,290', '184', '32', '$42,680', '4.9', '$52,100', 9, '$12,480', 7, '$3,940', 14], 'clearwater-plumbing': ['$61,840', '142', '21', '$28,460', '4.8', '$38,720', 6, '$9,180', 4, '$2,860', 11], 'lowcountry-wash-co': ['$47,290', '216', '18', '$16,940', '4.9', '$22,180', 5, '$4,920', 8, '$2,140', 19], 'palmetto-electric': ['$93,480', '118', '27', '$64,820', '4.9', '$71,440', 8, '$19,320', 3, '$5,280', 8], 'harbor-shine': ['$39,620', '284', '16', '$12,740', '5.0', '$18,650', 4, '$3,180', 5, '$1,420', 26] }[tenantId];
  const saved = state.get(tenantId);
  const amount = (value) => Number(String(value || '').replace(/[^\d.-]/g, '')) || 0;
  const money = (value) => `$${Math.round(value).toLocaleString('en-US')}`;
  const paid = saved.invoices.reduce((sum, item) => sum + Number(item.paidAmount || (item.status === 'Paid' ? item.amount : 0) || 0), 0);
  const estimateValue = saved.estimates.reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const dueValue = saved.invoices.filter((item) => item.status !== 'Paid').reduce((sum, item) => sum + Number(item.balance ?? item.amount ?? 0), 0);
  const satisfaction = saved.reviews.length ? (saved.reviews.reduce((sum, item) => sum + item.rating, 0) / saved.reviews.length).toFixed(1) : base[4];
  return { tenant: tenants[tenantId], metrics: { revenue: money(amount(base[0]) + paid), jobs: String(Number(base[1]) + saved.jobs.length), estimates: String(Number(base[2]) + saved.estimates.length), estimateValue: money(amount(base[3]) + estimateValue), satisfaction, pipeline: money(amount(base[5]) + estimateValue) }, actions: { estimates: base[6] + saved.estimates.filter((item) => item.status !== 'Accepted').length, estimateValue: money(amount(base[7]) + estimateValue), invoices: base[8] + saved.invoices.filter((item) => item.status !== 'Paid').length, invoiceValue: money(amount(base[9]) + dueValue), renewals: base[10] + saved.plans.filter((item) => item.status === 'Renewing soon').length }, completedTasks: saved.completedTasks, lastAction: saved.lastAction };
};
const reportsFor = (tenantId) => {
  const saved = state.get(tenantId);
  const money = (value) => `$${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
  const converted = saved.leads.filter((item) => item.status === 'Converted').length;
  const paid = saved.invoices.filter((item) => item.status === 'Paid').reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const recurring = saved.plans.filter((item) => item.status === 'Active').reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const satisfaction = saved.reviews.length ? `${(saved.reviews.reduce((sum, item) => sum + item.rating, 0) / saved.reviews.length).toFixed(1)} / 5` : 'No reviews';
  return { tenant: tenants[tenantId], period: 'All development activity', metrics: [{ label: 'New leads', value: String(saved.leads.length), detail: `${converted} converted to jobs` }, { label: 'Lead conversion', value: saved.leads.length ? `${Math.round((converted / saved.leads.length) * 100)}%` : '0%', detail: 'Captured leads becoming scheduled work' }, { label: 'Scheduled jobs', value: String(saved.jobs.filter((item) => item.status !== 'Canceled').length), detail: 'Tenant-owned dispatch records' }, { label: 'Cash collected', value: money(paid), detail: 'Paid invoices from quote-to-cash' }, { label: 'Monthly recurring', value: money(recurring), detail: 'Active service plans' }, { label: 'Customer touchpoints', value: String(saved.activities.length), detail: 'Logged calls, messages, and notes' }, { label: 'Customer satisfaction', value: satisfaction, detail: `${saved.reviews.length} completed-job reviews` }] };
};
const recordsFor = (tenantId, type, search = '') => {
  const business = tenants[tenantId];
  const customerNames = ['Michael Torres', 'Aisha Patel', 'Sarah Chen', 'Daniel Brooks', 'Lakeside Property Group'];
  const customers = [...customerNames.map((name, index) => ({ id: `${tenantId}_customer_${index + 1}`, tenantId, name, phone: ['843-555-0148', '843-555-0192', '843-555-0130', '843-555-0177', '843-555-0104'][index], location: ['105 King St', '38 Coming St', '12 Broad St', '214 Rutledge Ave', '17 Wentworth Ave'][index], lastService: ['Yesterday', 'Today', 'Aug 28', 'Aug 22', 'Aug 18'][index], status: index === 4 ? 'Lead' : 'Active' })), ...state.get(tenantId).customers];
  const leads = [{ id: `${tenantId}_lead_1`, name: 'Lakeside Property Group', service: business.serviceLabel, source: 'Website landing page', age: '3 hrs ago', value: '$4,800' }, { id: `${tenantId}_lead_2`, name: 'Maya Robinson', service: 'Emergency service', source: 'Google Business Profile', age: 'Yesterday', value: '$680' }, ...state.get(tenantId).leads];
  const estimates = [{ id: 'EST-1048', customer: 'Michael Torres', service: 'Annual service', value: '$1,240', status: 'Follow up', sent: '2 days ago' }, { id: 'EST-1045', customer: 'Sarah Chen', service: 'Kitchen remodel', value: '$4,820', status: 'Accepted', sent: 'Yesterday' }, { id: 'EST-1042', customer: 'Daniel Brooks', service: 'Repair visit', value: '$680', status: 'Viewed', sent: 'Aug 29' }, ...state.get(tenantId).estimates];
  const invoices = [{ id: 'INV-3021', customer: 'Lakeside Property Group', value: '$1,840', status: 'Overdue', due: 'Sep 4' }, { id: 'INV-3018', customer: 'Aisha Patel', value: '$620', status: 'Due soon', due: 'Sep 12' }, { id: 'INV-3009', customer: 'Michael Torres', value: '$289', status: 'Paid', due: 'Aug 30' }, ...state.get(tenantId).invoices];
  const plans = [{ id: 'PLAN-118', customer: 'Michael Torres', service: `${business.serviceLabel} maintenance`, value: '$149 / month', status: 'Renewing soon', renewal: 'Sep 18' }, { id: 'PLAN-113', customer: 'Aisha Patel', service: 'Priority service plan', value: '$89 / month', status: 'Active', renewal: 'Oct 4' }, ...state.get(tenantId).plans];
  const activities = [{ id: 'ACT-901', customer: 'Michael Torres', channel: 'Phone call', note: 'Confirmed annual maintenance window.', at: 'Today, 9:14 AM', status: 'Logged' }, { id: 'ACT-898', customer: 'Aisha Patel', channel: 'SMS', note: 'Sent arrival-window reminder.', at: 'Yesterday, 4:30 PM', status: 'Sent' }, ...state.get(tenantId).activities];
  const team = teamFor(tenantId);
  const catalog = catalogFor(tenantId);
  const notifications = notificationsFor(tenantId);
  const assets = state.get(tenantId).assets;
  const reviews = state.get(tenantId).reviews;
  const dispatch = [{ id: 'JOB-2194', customer: 'Michael Torres', service: 'Annual maintenance', technician: 'Alex Rivera', status: 'Confirmed', time: '8:00 – 10:00 AM' }, { id: 'JOB-2195', customer: 'Aisha Patel', service: 'Repair visit', technician: 'Marcus Thompson', status: 'En route', time: '10:30 – 12:00 PM' }, { id: 'JOB-2196', customer: 'Lakeside Property Group', service: 'Installation', technician: null, status: 'Unassigned', time: '1:00 – 4:00 PM' }, ...state.get(tenantId).jobs];
  const requests = state.get(tenantId).requests;
  const materials = state.get(tenantId).materials.map((item) => ({ ...item, status: item.onHand <= item.reorderPoint ? 'Low stock' : 'In stock', stockValue: `$${(item.onHand * item.unitCost).toFixed(2)}` }));
  const purchaseOrders = state.get(tenantId).purchaseOrders.map((item) => ({ ...item, total: `$${(item.quantity * item.unitCost).toFixed(2)}` }));
  const laborEntries = state.get(tenantId).laborEntries;
  const messages = state.get(tenantId).messages;
  const jobCosts = state.get(tenantId).jobs.map((job) => { const materialCost = (job.materials || []).reduce((sum, item) => sum + (Number(item.quantity) * Number(item.unitCost)), 0); const laborCost = laborEntries.filter((item) => item.jobId === job.id).reduce((sum, item) => sum + (Number(item.hours) * Number(item.hourlyRate)), 0); const estimate = state.get(tenantId).estimates.find((item) => item.id === job.estimateId); const invoice = state.get(tenantId).invoices.find((item) => item.estimateId === job.estimateId); const revenue = Number(invoice?.amount || estimate?.amount || 0); const totalCost = materialCost + laborCost; const margin = revenue - totalCost; return { id: `COST-${job.id}`, jobId: job.id, customer: job.customer, service: job.service, revenue: `$${revenue.toFixed(2)}`, materialCost: `$${materialCost.toFixed(2)}`, laborCost: `$${laborCost.toFixed(2)}`, totalCost: `$${totalCost.toFixed(2)}`, grossMargin: `$${margin.toFixed(2)}`, marginPercent: revenue ? `${((margin / revenue) * 100).toFixed(1)}%` : 'N/A', status: job.status }; });
  const payments = state.get(tenantId).payments;
  const all = { customers, leads, estimates, invoices, payments, plans, activities, dispatch, team, catalog, notifications, assets, reviews, requests, materials, purchaseOrders, 'purchase-orders': purchaseOrders, 'job-costs': jobCosts, messages }[type] || [];
  const q = search.trim().toLowerCase();
  return q ? all.filter((item) => Object.values(item).some((value) => String(value || '').toLowerCase().includes(q))) : all;
};
const exportableTypes = new Set(['customers', 'leads', 'estimates', 'invoices', 'payments', 'plans', 'activities', 'dispatch', 'assets', 'reviews', 'requests', 'materials', 'purchaseOrders', 'job-costs', 'messages']);
const csvCell = (value) => `"${String(value ?? '').replace(/"/g, '""')}"`;
const csvFor = (tenantId, type) => { const items = recordsFor(tenantId, type); const keys = [...new Set(items.flatMap((item) => Object.keys(item)))]; return [keys.map(csvCell).join(','), ...items.map((item) => keys.map((key) => csvCell(item[key])).join(','))].join('\n'); };
const customerProfileFor = (tenantId, customerId) => { const customer = recordsFor(tenantId, 'customers').find((item) => item.id === customerId); if (!customer) return null; const saved = state.get(tenantId); const matches = (type) => recordsFor(tenantId, type).filter((item) => item.customerId === customer.id || String(item.customer || '').toLowerCase() === customer.name.toLowerCase()); const locations = [{ id: `${customer.id}_primary`, customerId: customer.id, label: 'Primary service address', address: customer.location }].concat(saved.locations.filter((item) => item.customerId === customer.id)); const requests = saved.requests.filter((item) => item.customerId === customer.id || item.customer.toLowerCase() === customer.name.toLowerCase()); return { customer, locations, jobs: matches('dispatch'), assets: matches('assets'), estimates: matches('estimates'), invoices: matches('invoices'), plans: matches('plans'), activities: matches('activities'), requests }; };
const customerPortalFor = (tenantId, customerId) => { const profile = customerProfileFor(tenantId, customerId); if (!profile) return null; return { customer: { name: profile.customer.name, location: profile.customer.location }, locations: profile.locations.map((item) => ({ label: item.label, address: item.address })), jobs: profile.jobs.map((item) => ({ service: item.service, status: item.status, time: item.time, technician: item.technician || null })), assets: profile.assets.map((item) => ({ name: item.name, serial: item.serial, installed: item.installed, status: item.status })), estimates: profile.estimates.map((item) => ({ service: item.service, value: item.value, status: item.status, ...(state.get(tenantId).estimates.some((saved) => saved.id === item.id) && item.status === 'Draft' ? { id: item.id, estimateApprovalToken: issueEstimateToken(item) } : {}) })), invoices: profile.invoices.map((item) => ({ value: item.value, status: item.status, due: item.due || null, balance: item.balance ?? (item.status === 'Paid' ? 0 : item.amount ?? null) })), plans: profile.plans.map((item) => ({ service: item.service, value: item.value, status: item.status, renewal: item.renewal })) }; };
const scheduleConflictFor = (tenantId, jobId, technician, time) => state.get(tenantId).jobs.find((item) => item.id !== jobId && item.technician === technician && item.time === time && !['Completed', 'Canceled'].includes(item.status));
const sendStatic = (req, res) => {
  const requested = decodeURIComponent(new URL(req.url, `http://${req.headers.host}`).pathname);
  const relative = requested === '/' ? 'index.html' : requested.replace(/^\/+/, '');
  const file = normalize(join(ROOT, relative));
  if (!file.startsWith(ROOT + sep) || !existsSync(file) || !statSync(file).isFile()) return json(res, 404, { error: 'not_found' });
  res.writeHead(200, { 'content-type': MIME[extname(file)] || 'application/octet-stream', 'cache-control': 'no-store' }); createReadStream(file).pipe(res);
};

const server = createServer(async (req, res) => {
  try {
    const requestUrl = new URL(req.url, `http://${req.headers.host}`);
    const pathname = requestUrl.pathname;
    const origin = req.headers.origin;
    if (origin && ALLOWED_ORIGINS.has(origin)) { res.setHeader('access-control-allow-origin', origin); res.setHeader('vary', 'Origin'); }
    if (pathname === '/api/public/invoice' && req.method === 'GET') { const claims = readInvoiceToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_invoice_token' }); const invoice = state.get(claims.tenantId).invoices.find((item) => item.id === claims.invoiceId); if (!invoice) return json(res, 404, { error: 'invoice_not_found' }); return json(res, 200, { customer: invoice.customer, value: invoice.value, amount: invoice.amount, balance: invoice.balance ?? invoice.amount, status: invoice.status, due: invoice.due }); }
    if (pathname === '/api/public/invoice/payment-intent' && req.method === 'POST') { const claims = readInvoiceToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_invoice_token' }); const saved = state.get(claims.tenantId); const invoice = saved.invoices.find((item) => item.id === claims.invoiceId); if (!invoice) return json(res, 404, { error: 'invoice_not_found' }); const idempotencyKey = String(req.headers['idempotency-key'] || '').trim().slice(0, 100); if (idempotencyKey) { const existing = saved.paymentIntents.find((item) => item.invoiceId === invoice.id && item.idempotencyKey === idempotencyKey); if (existing) return json(res, 200, { ...existing, duplicate: true }); } const body = await readBody(req); const amount = Number(body.amount); const balance = Number(invoice.balance ?? invoice.amount ?? 0); if (invoice.status === 'Paid' || !Number.isFinite(amount) || amount <= 0 || amount > balance || !['Card', 'ACH'].includes(body.method)) return json(res, 422, { error: 'valid_payment_amount_and_method_required' }); const intent = { id: `PI-${Date.now()}`, tenantId: claims.tenantId, invoiceId: invoice.id, customer: invoice.customer, amount, method: body.method, status: 'Pending provider', createdAt: new Date().toISOString(), ...(idempotencyKey ? { idempotencyKey } : {}) }; saved.paymentIntents.unshift(intent); recordActivity(saved, invoice.customer, 'Payment', `Customer payment intent for $${amount.toFixed(2)} created via ${body.method}; provider confirmation pending.`, intent.status); persist(); return json(res, 201, intent); }
    const requiredPermission = permissionFor(pathname, req.method); if (requiredPermission) { const claims = authenticate(req); if (claims && !allowed(claims, requiredPermission)) return json(res, 403, { error: 'forbidden', requiredPermission }); }
    if (pathname === '/api/public/leads' && req.method === 'OPTIONS') { if (!origin || !ALLOWED_ORIGINS.has(origin)) return json(res, 403, { error: 'origin_not_allowed' }); res.writeHead(204, { 'access-control-allow-origin': origin, 'access-control-allow-methods': 'POST, OPTIONS', 'access-control-allow-headers': 'content-type, idempotency-key', 'vary': 'Origin' }); return res.end(); }
    if (pathname === '/api/health' && req.method === 'GET') return json(res, 200, { ok: true, service: 'northstar-api', version: '0.2.0' });
    if (pathname === '/api/auth/demo-login' && req.method === 'POST') {
      const body = await readBody(req); const service = body.service || requestUrl.searchParams.get('service') || 'default'; const role = String(body.role || requestUrl.searchParams.get('role') || 'owner').toLowerCase(); if (!demoStaff[role]) return json(res, 422, { error: 'invalid_demo_role' }); const tenantId = serviceTenant[service] || serviceTenant.default; const owner = { ...demoStaff[role], tenantId }; return json(res, 200, { token: issueToken(owner), owner: { id: owner.id, name: owner.name, role: owner.role }, tenant: tenants[tenantId], permissions: rolePermissions[role] });
    }
    if (pathname === '/api/auth/logout' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); revokedTokens.add((req.headers.authorization || '').slice(7)); return json(res, 200, { ok: true }); }
    if (pathname === '/api/public/leads' && req.method === 'POST') { const body = await readBody(req); if (body.website) return json(res, 422, { error: 'invalid_submission' }); if (!allowPublicLead(req)) return json(res, 429, { error: 'rate_limited' }); const service = body.service || requestUrl.searchParams.get('service') || 'default'; const tenantId = serviceTenant[service] || serviceTenant.default; const saved = state.get(tenantId); const idempotencyKey = String(req.headers['idempotency-key'] || body.idempotencyKey || '').trim().slice(0, 100); if (idempotencyKey) { const existing = saved.leads.find((item) => item.idempotencyKey === idempotencyKey); if (existing) return json(res, 200, { id: existing.id, received: true, duplicate: true, tenant: tenants[tenantId] }); } if (!body.name || (!body.email && !body.phone)) return json(res, 422, { error: 'name_and_contact_required' }); const lead = { id: `${tenantId}_lead_${Date.now()}`, tenantId, name: String(body.name).slice(0, 100), service: String(body.requestedService || tenants[tenantId].serviceLabel).slice(0, 80), source: String(body.source || 'Landing page').slice(0, 80), contact: String(body.email || body.phone).slice(0, 120), age: 'Just now', value: '$0', status: 'New', ...(idempotencyKey ? { idempotencyKey } : {}) }; saved.leads.unshift(lead); recordActivity(saved, lead.name, 'Web form', `New ${lead.service} lead captured from ${lead.source}.`, 'Received'); persist(); return json(res, 201, { id: lead.id, received: true, tenant: tenants[tenantId] }); }
    if (pathname === '/api/public/job-status' && req.method === 'GET') { const claims = readJobStatusToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_status_token' }); const job = state.get(claims.tenantId).jobs.find((item) => item.id === claims.jobId); if (!job) return json(res, 404, { error: 'job_not_found' }); return json(res, 200, { service: job.service, status: job.status, time: job.time, technician: job.technician || null }); }
    if (pathname === '/api/public/estimate' && req.method === 'GET') { const claims = readEstimateToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_estimate_token' }); const estimate = state.get(claims.tenantId).estimates.find((item) => item.id === claims.estimateId); if (!estimate) return json(res, 404, { error: 'estimate_not_found' }); return json(res, 200, { customer: estimate.customer, service: estimate.service, value: estimate.value, status: estimate.status }); }
    if (pathname === '/api/public/estimate/approve' && req.method === 'POST') { const claims = readEstimateToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_estimate_token' }); const saved = state.get(claims.tenantId); const estimate = saved.estimates.find((item) => item.id === claims.estimateId); if (!estimate) return json(res, 404, { error: 'estimate_not_found' }); if (estimate.status === 'Accepted') return json(res, 200, { status: estimate.status }); if (estimate.status !== 'Draft') return json(res, 409, { error: 'estimate_not_approvable' }); estimate.status = 'Accepted'; estimate.approvedAt = new Date().toISOString(); recordActivity(saved, estimate.customer, 'Estimate', `Customer approved ${estimate.service} estimate for ${estimate.value}.`, 'Approved'); persist(); return json(res, 200, { status: estimate.status }); }
    if (pathname === '/api/public/technician-job' && req.method === 'GET') { const claims = readTechnicianToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_technician_token' }); const job = state.get(claims.tenantId).jobs.find((item) => item.id === claims.jobId); if (!job || job.technician !== claims.technician) return json(res, 404, { error: 'job_not_found' }); return json(res, 200, { id: job.id, customer: job.customer, service: job.service, time: job.time, technician: job.technician, status: job.status, checklist: job.checklist || [], completionNote: job.completionNote || null }); }
    if (pathname === '/api/public/technician-job/status' && req.method === 'POST') { const claims = readTechnicianToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_technician_token' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === claims.jobId); if (!job || job.technician !== claims.technician) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); const allowed = ['En route', 'In progress']; if (!allowed.includes(body.status) || job.status === 'Completed' || job.status === 'Canceled') return json(res, 409, { error: 'invalid_technician_status' }); job.status = body.status; const now = new Date().toISOString(); job.updatedAt = now; if (body.status === 'En route') job.enRouteAt = now; if (body.status === 'In progress') job.startedAt = now; recordActivity(saved, job.customer || job.customerId, 'Technician update', `${job.technician} marked ${job.service} ${body.status.toLowerCase()}.`, body.status); persist(); return json(res, 200, job); }
    if (pathname === '/api/public/technician-job/checklist' && req.method === 'POST') { const claims = readTechnicianToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_technician_token' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === claims.jobId); if (!job || job.technician !== claims.technician) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); const index = Number(body.index); if (!Array.isArray(job.checklist) || !Number.isInteger(index) || index < 0 || index >= job.checklist.length) return json(res, 422, { error: 'invalid_checklist_item' }); job.checklist[index].completed = Boolean(body.completed); job.updatedAt = new Date().toISOString(); persist(); return json(res, 200, { checklist: job.checklist }); }
    if (pathname === '/api/public/technician-job/complete' && req.method === 'POST') { const claims = readTechnicianToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_technician_token' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === claims.jobId); if (!job || job.technician !== claims.technician) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); if (job.status === 'Canceled') return json(res, 409, { error: 'canceled_job_cannot_complete' }); if (Array.isArray(job.checklist) && job.checklist.some((item) => !item.completed)) return json(res, 409, { error: 'checklist_incomplete', remaining: job.checklist.filter((item) => !item.completed).map((item) => item.label) }); if (!body.note || String(body.note).trim().length < 3) return json(res, 422, { error: 'completion_note_required' }); job.status = 'Completed'; job.completionNote = String(body.note).slice(0, 500); job.completedAt = new Date().toISOString(); job.updatedAt = job.completedAt; recordActivity(saved, job.customer || job.customerId, 'Job completed', `${job.service} completed by ${job.technician}. ${job.completionNote}`, 'Completed'); persist(); return json(res, 200, { status: job.status, completedAt: job.completedAt }); }
    if (pathname === '/api/public/customer-portal' && req.method === 'GET') { const claims = readCustomerToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_customer_token' }); const portal = customerPortalFor(claims.tenantId, claims.customerId); if (!portal) return json(res, 404, { error: 'customer_not_found' }); return json(res, 200, portal); }
    if (pathname === '/api/public/review' && req.method === 'GET') { const claims = readReviewToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_review_token' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === claims.jobId); if (!job || job.status !== 'Completed') return json(res, 404, { error: 'completed_job_not_found' }); const review = saved.reviews.find((item) => item.jobId === job.id); return json(res, 200, { service: job.service, customer: job.customer, submitted: Boolean(review), rating: review?.rating || null }); }
    if (pathname === '/api/public/review' && req.method === 'POST') { const claims = readReviewToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_review_token' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === claims.jobId); if (!job || job.status !== 'Completed') return json(res, 404, { error: 'completed_job_not_found' }); if (saved.reviews.some((item) => item.jobId === job.id)) return json(res, 409, { error: 'review_already_submitted' }); const body = await readBody(req); const rating = Number(body.rating); if (!Number.isInteger(rating) || rating < 1 || rating > 5) return json(res, 422, { error: 'rating_must_be_1_to_5' }); const review = { id: `REV-${Date.now()}`, tenantId: claims.tenantId, jobId: job.id, customer: job.customer, service: job.service, rating, comment: String(body.comment || '').slice(0, 500), submittedAt: new Date().toISOString() }; saved.reviews.unshift(review); recordActivity(saved, job.customer || job.customerId, 'Review', `Customer left a ${rating}/5 review for ${job.service}.`, `${rating}/5`); persist(); return json(res, 201, { rating: review.rating, submitted: true }); }
    if (pathname === '/api/public/customer-portal/request' && req.method === 'POST') { const claims = readCustomerToken(requestUrl.searchParams.get('token')); if (!claims) return json(res, 401, { error: 'invalid_customer_token' }); const profile = customerProfileFor(claims.tenantId, claims.customerId); if (!profile) return json(res, 404, { error: 'customer_not_found' }); const body = await readBody(req); const types = ['Reschedule request', 'Question']; if (!types.includes(body.type) || !body.message || String(body.message).trim().length < 3) return json(res, 422, { error: 'valid_request_type_and_message_required' }); if (body.jobId && !profile.jobs.some((item) => item.id === body.jobId)) return json(res, 404, { error: 'job_not_found' }); const saved = state.get(claims.tenantId); const request = { id: `REQ-${Date.now()}`, tenantId: claims.tenantId, customerId: profile.customer.id, customer: profile.customer.name, jobId: body.jobId || null, type: body.type, message: String(body.message).slice(0, 500), status: 'Open', createdAt: new Date().toISOString() }; saved.requests.unshift(request); recordActivity(saved, request.customer, 'Customer request', `${request.type}: ${request.message}`, 'Open'); persist(); return json(res, 201, { id: request.id, status: request.status }); }
    if (pathname === '/api/session' && req.method === 'GET') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); return json(res, 200, { owner: { id: claims.sub, name: demoStaff[claims.role].name, role: claims.role }, tenant: tenants[claims.tenantId], permissions: rolePermissions[claims.role] }); }
    if (pathname === '/api/dashboard' && req.method === 'GET') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); return json(res, 200, dashboardFor(claims.tenantId)); }
    if (pathname === '/api/reports/overview' && req.method === 'GET') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); return json(res, 200, reportsFor(claims.tenantId)); }
    if (pathname === '/api/export' && req.method === 'GET') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const type = requestUrl.searchParams.get('type') || 'customers'; if (!exportableTypes.has(type)) return json(res, 422, { error: 'unsupported_export_type' }); res.writeHead(200, { 'content-type': 'text/csv; charset=utf-8', 'content-disposition': `attachment; filename="northstar-${type}.csv"`, 'cache-control': 'no-store' }); return res.end(csvFor(claims.tenantId, type)); }
    const recordsMatch = pathname.match(/^\/api\/(customers|leads|estimates|invoices|payments|plans|activities|dispatch|team|catalog|notifications|assets|reviews|requests|materials|purchase-orders|job-costs|messages)$/);
    if (recordsMatch && req.method === 'GET') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); return json(res, 200, { items: recordsFor(claims.tenantId, recordsMatch[1], requestUrl.searchParams.get('search') || ''), tenantId: claims.tenantId }); }
    const notificationReadMatch = pathname.match(/^\/api\/notifications\/([^/]+)\/read$/);
    if (notificationReadMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const notification = notificationsFor(claims.tenantId).find((item) => item.id === notificationReadMatch[1]); if (!notification) return json(res, 404, { error: 'notification_not_found' }); const saved = state.get(claims.tenantId); if (!saved.notificationReads.includes(notification.id)) saved.notificationReads.push(notification.id); persist(); return json(res, 200, { id: notification.id, read: true }); }
    const requestResolveMatch = pathname.match(/^\/api\/requests\/(REQ-[^/]+)\/resolve$/);
    if (requestResolveMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const request = saved.requests.find((item) => item.id === requestResolveMatch[1]); if (!request) return json(res, 404, { error: 'request_not_found' }); const body = await readBody(req); request.status = 'Resolved'; request.resolution = String(body.note || 'Owner follow-up completed.').slice(0, 500); request.resolvedAt = new Date().toISOString(); recordActivity(saved, request.customer, 'Customer request', `${request.type} resolved. ${request.resolution}`, 'Resolved'); persist(); return json(res, 200, request); }
    const customerProfileMatch = pathname.match(/^\/api\/customers\/([^/]+)$/);
    if (customerProfileMatch && req.method === 'GET') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const profile = customerProfileFor(claims.tenantId, customerProfileMatch[1]); if (!profile) return json(res, 404, { error: 'customer_not_found' }); return json(res, 200, profile); }
    const customerLocationMatch = pathname.match(/^\/api\/customers\/([^/]+)\/locations$/);
    if (customerLocationMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const customer = recordsFor(claims.tenantId, 'customers').find((item) => item.id === customerLocationMatch[1]); if (!customer) return json(res, 404, { error: 'customer_not_found' }); const body = await readBody(req); if (!body.address || String(body.address).trim().length < 5) return json(res, 422, { error: 'address_required' }); const saved = state.get(claims.tenantId); const location = { id: `LOC-${Date.now()}`, tenantId: claims.tenantId, customerId: customer.id, label: String(body.label || 'Service address').slice(0, 80), address: String(body.address).slice(0, 180) }; saved.locations.unshift(location); recordActivity(saved, customer.name, 'Location', `Added ${location.label}: ${location.address}.`, 'Recorded'); persist(); return json(res, 201, location); }
    if (pathname === '/api/customers' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); if (!body.name || !body.phone) return json(res, 422, { error: 'name_and_phone_required' }); const customer = { id: `${claims.tenantId}_customer_${Date.now()}`, tenantId: claims.tenantId, name: String(body.name).slice(0, 100), phone: String(body.phone).slice(0, 40), location: String(body.location || 'Address pending').slice(0, 120), lastService: 'New customer', status: 'Active' }; state.get(claims.tenantId).customers.unshift(customer); persist(); return json(res, 201, customer); }
    if (pathname === '/api/assets' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); if (!body.customer || !body.name) return json(res, 422, { error: 'customer_and_asset_name_required' }); const saved = state.get(claims.tenantId); const asset = { id: `ASSET-${Date.now()}`, tenantId: claims.tenantId, customer: String(body.customer).slice(0, 100), name: String(body.name).slice(0, 120), serial: String(body.serial || 'Not recorded').slice(0, 100), installed: String(body.installed || 'Date pending').slice(0, 40), status: 'Active' }; saved.assets.unshift(asset); recordActivity(saved, asset.customer, 'Asset', `Added ${asset.name} to the customer record.`, 'Recorded'); persist(); return json(res, 201, asset); }
    if (pathname === '/api/leads' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); if (!body.name || !body.source) return json(res, 422, { error: 'name_and_source_required' }); const lead = { id: `${claims.tenantId}_lead_${Date.now()}`, tenantId: claims.tenantId, name: String(body.name).slice(0, 100), service: String(body.service || tenants[claims.tenantId].serviceLabel).slice(0, 80), source: String(body.source).slice(0, 80), age: 'Just now', value: '$0' }; state.get(claims.tenantId).leads.unshift(lead); persist(); return json(res, 201, lead); }
    const leadConvertMatch = pathname.match(/^\/api\/leads\/([^/]+)\/convert$/);
    if (leadConvertMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const saved = state.get(claims.tenantId); const lead = saved.leads.find((item) => item.id === leadConvertMatch[1]); if (!lead) return json(res, 404, { error: 'lead_not_found' }); if (lead.convertedJobId) return json(res, 409, { error: 'lead_already_converted', jobId: lead.convertedJobId }); if (!body.time) return json(res, 422, { error: 'time_required' }); let customer = saved.customers.find((item) => item.name.toLowerCase() === lead.name.toLowerCase()); if (!customer) { customer = { id: `${claims.tenantId}_customer_${Date.now()}`, tenantId: claims.tenantId, name: lead.name, phone: lead.contact || 'Contact pending', location: 'Address pending', lastService: 'New customer', status: 'Active' }; saved.customers.unshift(customer); } const job = { id: `${claims.tenantId}_job_${Date.now()}`, tenantId: claims.tenantId, leadId: lead.id, customerId: customer.id, customer: customer.name, service: lead.service, technician: null, status: 'Unassigned', time: String(body.time), checklist: defaultChecklist() }; saved.jobs.unshift(job); lead.status = 'Converted'; lead.convertedCustomerId = customer.id; lead.convertedJobId = job.id; persist(); return json(res, 201, { lead, customer, job, customerPortalToken: issueJobStatusToken(job) }); }
    if (pathname === '/api/jobs' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); if (!body.customerId || !body.time) return json(res, 422, { error: 'customer_and_time_required' }); const saved = state.get(claims.tenantId); const customer = recordsFor(claims.tenantId, 'customers').find((item) => item.id === String(body.customerId)); const job = { id: `${claims.tenantId}_job_${Date.now()}`, tenantId: claims.tenantId, customerId: String(body.customerId), customer: customer?.name || String(body.customerId).slice(0, 100), service: String(body.service || tenants[claims.tenantId].serviceLabel).slice(0, 100), technician: null, status: 'Unassigned', time: String(body.time), checklist: defaultChecklist() }; saved.jobs.unshift(job); persist(); return json(res, 201, { ...job, customerPortalToken: issueJobStatusToken(job) }); }
    if (pathname === '/api/plans' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const amount = Number(body.amount); if (!body.customer || !body.service || !Number.isFinite(amount) || amount <= 0 || !body.renewal) return json(res, 422, { error: 'customer_service_amount_and_renewal_required' }); const plan = { id: `PLAN-${Date.now()}`, tenantId: claims.tenantId, customer: String(body.customer).slice(0, 100), service: String(body.service).slice(0, 100), value: `$${amount.toFixed(2)} / month`, amount, status: 'Active', renewal: String(body.renewal).slice(0, 40) }; state.get(claims.tenantId).plans.unshift(plan); persist(); return json(res, 201, plan); }
    if (pathname === '/api/activities' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const channels = ['Phone call', 'SMS', 'Email', 'Note']; if (!body.customer || !body.note || !channels.includes(body.channel || 'Note')) return json(res, 422, { error: 'customer_note_and_valid_channel_required' }); const activity = { id: `ACT-${Date.now()}`, tenantId: claims.tenantId, customer: String(body.customer).slice(0, 100), channel: body.channel || 'Note', note: String(body.note).slice(0, 500), at: 'Just now', status: body.channel === 'Note' ? 'Logged' : 'Queued' }; state.get(claims.tenantId).activities.unshift(activity); persist(); return json(res, 201, activity); }
    if (pathname === '/api/messages' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const channels = ['SMS', 'Email']; if (!body.customer || !channels.includes(body.channel) || !body.message || String(body.message).trim().length < 3) return json(res, 422, { error: 'customer_channel_and_message_required' }); const saved = state.get(claims.tenantId); const message = { id: `MSG-${Date.now()}`, tenantId: claims.tenantId, customer: String(body.customer).slice(0, 100), channel: body.channel, message: String(body.message).slice(0, 1000), status: 'Queued (provider pending)', queuedAt: new Date().toISOString() }; saved.messages.unshift(message); recordActivity(saved, message.customer, message.channel, `Outbound ${message.channel} message queued: ${message.message}`, message.status); persist(); return json(res, 201, message); }
    const planRenewMatch = pathname.match(/^\/api\/plans\/(PLAN-[^/]+)\/renew$/);
    if (planRenewMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const plan = saved.plans.find((item) => item.id === planRenewMatch[1]); if (!plan) return json(res, 404, { error: 'plan_not_found' }); const body = await readBody(req); plan.status = 'Active'; plan.renewedAt = new Date().toISOString(); let nextJob = null; if (body.time) { const customer = recordsFor(claims.tenantId, 'customers').find((item) => item.name.toLowerCase() === String(plan.customer).toLowerCase()); nextJob = { id: `${claims.tenantId}_job_${Date.now()}`, tenantId: claims.tenantId, customerId: customer?.id || null, customer: plan.customer, service: plan.service, technician: null, status: 'Unassigned', time: String(body.time).slice(0, 120), planId: plan.id, checklist: defaultChecklist() }; saved.jobs.unshift(nextJob); recordActivity(saved, plan.customer, 'Service plan', `Renewed ${plan.service} plan and scheduled the next visit for ${nextJob.time}.`, 'Renewed'); } persist(); return json(res, 200, { plan, nextJob }); }
    if (pathname === '/api/materials' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const unitCost = Number(body.unitCost); const onHand = Number(body.onHand); const reorderPoint = Number(body.reorderPoint ?? 0); if (!body.name || !Number.isFinite(unitCost) || unitCost < 0 || !Number.isInteger(onHand) || onHand < 0 || !Number.isInteger(reorderPoint) || reorderPoint < 0) return json(res, 422, { error: 'valid_material_name_and_stock_required' }); const saved = state.get(claims.tenantId); const material = { id: `MAT-${Date.now()}`, tenantId: claims.tenantId, name: String(body.name).slice(0, 120), sku: String(body.sku || '').slice(0, 60), unit: String(body.unit || 'each').slice(0, 30), unitCost, onHand, reorderPoint }; saved.materials.unshift(material); saved.inventoryTransactions.unshift({ id: `INVTX-${Date.now()}`, tenantId: claims.tenantId, materialId: material.id, type: 'Receipt', quantity: onHand, createdAt: new Date().toISOString() }); persist(); return json(res, 201, recordsFor(claims.tenantId, 'materials').find((item) => item.id === material.id)); }
    const jobMaterialsMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/materials$/);
    if (jobMaterialsMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === jobMaterialsMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); const quantity = Number(body.quantity); const material = saved.materials.find((item) => item.id === body.materialId); if (!material) return json(res, 404, { error: 'material_not_found' }); if (!Number.isInteger(quantity) || quantity <= 0 || quantity > material.onHand) return json(res, 422, { error: 'quantity_must_be_within_stock' }); material.onHand -= quantity; job.materials = job.materials || []; job.materials.push({ materialId: material.id, name: material.name, quantity, unitCost: material.unitCost }); const transaction = { id: `INVTX-${Date.now()}`, tenantId: claims.tenantId, materialId: material.id, jobId: job.id, type: 'Consumption', quantity: -quantity, createdAt: new Date().toISOString() }; saved.inventoryTransactions.unshift(transaction); recordActivity(saved, job.customer || job.customerId, 'Inventory', `Used ${quantity} ${material.unit} of ${material.name} on ${job.service}.`, material.onHand <= material.reorderPoint ? 'Low stock' : 'Consumed'); persist(); return json(res, 200, { job, material: recordsFor(claims.tenantId, 'materials').find((item) => item.id === material.id), transaction }); }
    if (pathname === '/api/purchase-orders' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const quantity = Number(body.quantity); const unitCost = Number(body.unitCost); const material = state.get(claims.tenantId).materials.find((item) => item.id === body.materialId); if (!material) return json(res, 404, { error: 'material_not_found' }); if (!body.vendor || !Number.isInteger(quantity) || quantity <= 0 || !Number.isFinite(unitCost) || unitCost < 0) return json(res, 422, { error: 'vendor_quantity_and_cost_required' }); const saved = state.get(claims.tenantId); const order = { id: `PO-${Date.now()}`, tenantId: claims.tenantId, vendor: String(body.vendor).slice(0, 120), materialId: material.id, material: material.name, quantity, unitCost, status: 'Open', createdAt: new Date().toISOString() }; saved.purchaseOrders.unshift(order); persist(); return json(res, 201, recordsFor(claims.tenantId, 'purchaseOrders').find((item) => item.id === order.id)); }
    const purchaseReceiveMatch = pathname.match(/^\/api\/purchase-orders\/([^/]+)\/receive$/);
    if (purchaseReceiveMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const order = saved.purchaseOrders.find((item) => item.id === purchaseReceiveMatch[1]); if (!order) return json(res, 404, { error: 'purchase_order_not_found' }); if (order.status === 'Received') return json(res, 409, { error: 'purchase_order_already_received' }); const material = saved.materials.find((item) => item.id === order.materialId); if (!material) return json(res, 404, { error: 'material_not_found' }); material.onHand += order.quantity; order.status = 'Received'; order.receivedAt = new Date().toISOString(); saved.inventoryTransactions.unshift({ id: `INVTX-${Date.now()}`, tenantId: claims.tenantId, materialId: material.id, purchaseOrderId: order.id, type: 'Purchase receipt', quantity: order.quantity, createdAt: order.receivedAt }); persist(); return json(res, 200, { order: recordsFor(claims.tenantId, 'purchaseOrders').find((item) => item.id === order.id), material: recordsFor(claims.tenantId, 'materials').find((item) => item.id === material.id) }); }
    const laborMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/labor$/);
    if (laborMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === laborMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); const hours = Number(body.hours); const hourlyRate = Number(body.hourlyRate); const technician = String(body.technician || job.technician || '').trim(); if (!technician || !Number.isFinite(hours) || hours <= 0 || hours > 24 || !Number.isFinite(hourlyRate) || hourlyRate < 0) return json(res, 422, { error: 'technician_hours_and_rate_required' }); const entry = { id: `LAB-${Date.now()}`, tenantId: claims.tenantId, jobId: job.id, customer: job.customer, technician: technician.slice(0, 80), hours, hourlyRate, cost: hours * hourlyRate, createdAt: new Date().toISOString() }; saved.laborEntries.unshift(entry); recordActivity(saved, job.customer || job.customerId, 'Labor', `Logged ${hours} labor hours for ${job.service} at $${hourlyRate.toFixed(2)}/hr.`, 'Logged'); persist(); return json(res, 201, { entry, jobCost: recordsFor(claims.tenantId, 'job-costs').find((item) => item.jobId === job.id) }); }
    const jobUpdateMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/(assign|status)$/);
    if (jobUpdateMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === jobUpdateMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); let eventNote = ''; if (jobUpdateMatch[2] === 'assign') { if (!body.technician || String(body.technician).length > 80) return json(res, 422, { error: 'technician_required' }); if (!teamFor(claims.tenantId).some((member) => member.name === body.technician)) return json(res, 422, { error: 'technician_not_on_team' }); const conflict = scheduleConflictFor(claims.tenantId, job.id, String(body.technician), job.time); if (conflict) return json(res, 409, { error: 'technician_schedule_conflict', conflictJobId: conflict.id, conflictTime: conflict.time }); job.technician = String(body.technician); if (job.status === 'Unassigned') job.status = 'Confirmed'; eventNote = `Assigned ${job.service} to ${job.technician}.`; } else { const allowed = ['Unassigned', 'Confirmed', 'En route', 'In progress', 'Completed', 'Canceled']; if (!allowed.includes(body.status)) return json(res, 422, { error: 'invalid_job_status' }); job.status = body.status; eventNote = `${job.service} marked ${job.status}.`; } job.updatedAt = new Date().toISOString(); recordActivity(saved, job.customer || job.customerId, 'Dispatch', eventNote, job.status); persist(); return json(res, 200, job); }
    const rescheduleMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/reschedule$/);
    if (rescheduleMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === rescheduleMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); if (!body.time || String(body.time).length > 120) return json(res, 422, { error: 'time_required' }); const conflict = job.technician && scheduleConflictFor(claims.tenantId, job.id, job.technician, String(body.time)); if (conflict) return json(res, 409, { error: 'technician_schedule_conflict', conflictJobId: conflict.id, conflictTime: conflict.time }); job.time = String(body.time); job.updatedAt = new Date().toISOString(); recordActivity(saved, job.customer || job.customerId, 'Dispatch', `${job.service} rescheduled to ${job.time}.`, job.status); persist(); return json(res, 200, job); }
    const techLinkMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/technician-link$/);
    if (techLinkMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const job = state.get(claims.tenantId).jobs.find((item) => item.id === techLinkMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); if (!job.technician) return json(res, 409, { error: 'technician_required_before_link' }); return json(res, 200, { url: `/technician.html?token=${encodeURIComponent(issueTechnicianToken(job))}`, expiresInHours: 24, technician: job.technician }); }
    const customerLinkMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/customer-link$/);
    if (customerLinkMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const job = state.get(claims.tenantId).jobs.find((item) => item.id === customerLinkMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); if (!job.customerId) return json(res, 409, { error: 'customer_required_before_link' }); if (!customerProfileFor(claims.tenantId, job.customerId)) return json(res, 404, { error: 'customer_not_found' }); return json(res, 200, { url: `/customer.html?token=${encodeURIComponent(issueCustomerToken(claims.tenantId, job.customerId))}`, expiresInHours: 72 }); }
    const reviewLinkMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/review-link$/);
    if (reviewLinkMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const job = state.get(claims.tenantId).jobs.find((item) => item.id === reviewLinkMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); if (job.status !== 'Completed') return json(res, 409, { error: 'completed_job_required' }); return json(res, 200, { url: `/review.html?token=${encodeURIComponent(issueReviewToken(job))}`, expiresInHours: 72 }); }
    const completeMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/complete$/);
    if (completeMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const job = saved.jobs.find((item) => item.id === completeMatch[1]); if (!job) return json(res, 404, { error: 'job_not_found' }); const body = await readBody(req); if (!job.technician) return json(res, 409, { error: 'technician_required_before_completion' }); if (job.status === 'Canceled') return json(res, 409, { error: 'canceled_job_cannot_complete' }); if (!body.note || String(body.note).trim().length < 3) return json(res, 422, { error: 'completion_note_required' }); job.status = 'Completed'; job.completionNote = String(body.note).slice(0, 500); job.completedAt = new Date().toISOString(); job.updatedAt = job.completedAt; recordActivity(saved, job.customer || job.customerId, 'Job completed', `${job.service} completed by ${job.technician}. ${job.completionNote}`, 'Completed'); persist(); return json(res, 200, job); }
    if (pathname === '/api/estimates' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const amount = Number(body.amount); if (!body.customer || !body.service || !Number.isFinite(amount) || amount <= 0) return json(res, 422, { error: 'customer_service_and_positive_amount_required' }); const estimate = { id: `EST-${Date.now()}`, tenantId: claims.tenantId, customer: String(body.customer).slice(0, 100), service: String(body.service).slice(0, 100), value: `$${amount.toFixed(2)}`, amount, status: 'Draft', sent: 'Just now' }; state.get(claims.tenantId).estimates.unshift(estimate); persist(); return json(res, 201, { ...estimate, estimateApprovalToken: issueEstimateToken(estimate) }); }
    const approveMatch = pathname.match(/^\/api\/estimates\/(EST-[^/]+)\/approve$/);
    if (approveMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const estimate = state.get(claims.tenantId).estimates.find((item) => item.id === approveMatch[1]); if (!estimate) return json(res, 404, { error: 'estimate_not_found' }); estimate.status = 'Accepted'; estimate.approvedAt = new Date().toISOString(); persist(); return json(res, 200, estimate); }
    const estimateConvertMatch = pathname.match(/^\/api\/estimates\/(EST-[^/]+)\/convert$/);
    if (estimateConvertMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const estimate = saved.estimates.find((item) => item.id === estimateConvertMatch[1]); if (!estimate) return json(res, 404, { error: 'estimate_not_found' }); if (estimate.status !== 'Accepted') return json(res, 409, { error: 'accepted_estimate_required' }); if (estimate.convertedJobId) return json(res, 409, { error: 'estimate_already_converted', jobId: estimate.convertedJobId }); const body = await readBody(req); if (!body.time) return json(res, 422, { error: 'time_required' }); const customer = recordsFor(claims.tenantId, 'customers').find((item) => item.name.toLowerCase() === estimate.customer.toLowerCase()); const job = { id: `${claims.tenantId}_job_${Date.now()}`, tenantId: claims.tenantId, estimateId: estimate.id, customerId: customer?.id || null, customer: estimate.customer, service: estimate.service, technician: null, status: 'Unassigned', time: String(body.time).slice(0, 120), checklist: defaultChecklist() }; saved.jobs.unshift(job); estimate.convertedJobId = job.id; recordActivity(saved, estimate.customer, 'Estimate', `Accepted ${estimate.service} estimate converted to a scheduled job for ${job.time}.`, 'Scheduled'); persist(); return json(res, 201, { estimate, job, customerPortalToken: issueJobStatusToken(job) }); }
    if (pathname === '/api/invoices' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const estimate = state.get(claims.tenantId).estimates.find((item) => item.id === body.estimateId); if (!estimate || estimate.status !== 'Accepted') return json(res, 422, { error: 'approved_estimate_required' }); const invoice = { id: `INV-${Date.now()}`, tenantId: claims.tenantId, customer: estimate.customer, estimateId: estimate.id, value: estimate.value, amount: estimate.amount, paidAmount: 0, balance: estimate.amount, status: 'Due', due: String(body.due || '30 days') }; state.get(claims.tenantId).invoices.unshift(invoice); persist(); return json(res, 201, invoice); }
    const paymentLinkMatch = pathname.match(/^\/api\/invoices\/(INV-[^/]+)\/payment-link$/);
    if (paymentLinkMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const invoice = state.get(claims.tenantId).invoices.find((item) => item.id === paymentLinkMatch[1]); if (!invoice) return json(res, 404, { error: 'invoice_not_found' }); if ((invoice.balance ?? invoice.amount ?? 0) <= 0 || invoice.status === 'Paid') return json(res, 409, { error: 'invoice_already_paid' }); return json(res, 200, { url: `/invoice.html?token=${encodeURIComponent(issueInvoiceToken(invoice))}`, expiresInHours: 72 }); }
    const payMatch = pathname.match(/^\/api\/invoices\/(INV-[^/]+)\/pay$/);
    if (payMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const saved = state.get(claims.tenantId); const invoice = saved.invoices.find((item) => item.id === payMatch[1]); if (!invoice) return json(res, 404, { error: 'invoice_not_found' }); const body = await readBody(req); const total = Number(invoice.amount || 0); const paidAmount = Number(invoice.paidAmount || (invoice.status === 'Paid' ? total : 0)); const balance = Math.max(0, total - paidAmount); const amount = body.amount === undefined ? balance : Number(body.amount); const methods = ['Card', 'Cash', 'Check', 'ACH', 'Other']; if (!Number.isFinite(amount) || amount <= 0 || amount > balance) return json(res, 422, { error: 'payment_must_be_between_zero_and_balance' }); if (body.method && !methods.includes(body.method)) return json(res, 422, { error: 'invalid_payment_method' }); const payment = { id: `PAY-${Date.now()}`, tenantId: claims.tenantId, invoiceId: invoice.id, customer: invoice.customer, amount, method: body.method || 'Other', reference: String(body.reference || '').slice(0, 100), paidAt: new Date().toISOString() }; saved.payments.unshift(payment); invoice.paidAmount = paidAmount + amount; invoice.balance = Math.max(0, total - invoice.paidAmount); invoice.status = invoice.balance === 0 ? 'Paid' : 'Partially paid'; if (invoice.status === 'Paid') invoice.paidAt = payment.paidAt; recordActivity(saved, invoice.customer, 'Payment', `${payment.method} payment of $${amount.toFixed(2)} recorded for invoice ${invoice.id}.`, invoice.status); persist(); return json(res, 200, { invoice, payment }); }
    const taskMatch = pathname.match(/^\/api\/tasks\/(\d+)$/);
    if (taskMatch && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); const index = Number(taskMatch[1]); const saved = state.get(claims.tenantId); saved.completedTasks = saved.completedTasks.filter((item) => item !== index); if (body.completed) saved.completedTasks.push(index); persist(); return json(res, 200, { completedTasks: saved.completedTasks }); }
    if (pathname === '/api/actions' && req.method === 'POST') { const claims = authenticate(req); if (!claims) return json(res, 401, { error: 'unauthorized' }); const body = await readBody(req); state.get(claims.tenantId).lastAction = { action: String(body.action || '').slice(0, 80), at: new Date().toISOString() }; persist(); return json(res, 201, { ok: true }); }
    if (req.method === 'GET') return sendStatic(req, res);
    return json(res, 405, { error: 'method_not_allowed' });
  } catch (error) { console.error(error); return json(res, 400, { error: 'bad_request' }); }
});
server.listen(PORT, () => console.log(`Northstar CRM running at http://localhost:${PORT}`));
