(() => {
  const link = document.querySelector('a[href="#settings"]');
  if (!link) return;
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
  const openSettings = async (event) => {
    event.preventDefault();
    const repository = window.northstarRepository;
    const drawer = document.querySelector('#record-drawer');
    const title = document.querySelector('#drawer-title');
    const list = document.querySelector('#record-list');
    if (!repository || !drawer || !title || !list) return;
    title.textContent = 'Workspace settings';
    drawer.dataset.view = 'settings';
    drawer.classList.add('open');
    drawer.setAttribute('aria-hidden', 'false');
    list.innerHTML = '<div class="empty-state">Loading workspace configuration…</div>';
    try {
      const [health, readiness] = repository.remote ? await Promise.all([repository.getIntegrationHealth(), repository.getReadiness()]) : [null, null];
      let workspace = repository.session?.tenant || repository.tenant || {};
      if (repository.remote) { try { workspace = (await repository.getWorkspaceSettings()).workspace || workspace; } catch {} }
      const serviceKey = new URLSearchParams(window.location.search).get('service') || repository.tenant?.slug || '';
      const origin = window.location.origin;
      const checks = health ? Object.entries(health.checks || {}).map(([key, value]) => `<article class="report-card"><div><span class="record-id">${escapeHtml(key)}</span><h3>${value ? 'Ready' : 'Needs attention'}</h3><p>${value ? 'The current operational check is healthy.' : 'Review deployment configuration before relying on this workflow.'}</p></div></article>`).join('') : '<article class="report-card"><div><span class="record-id">LOCAL PREVIEW</span><h3>Demo adapter active</h3><p>Settings shown here are local preview metadata. Production values are read from the authenticated tenant session.</p></div></article>';
      const readinessChecks = readiness ? Object.entries(readiness.checks || {}).map(([key, value]) => `<li><span>${escapeHtml(key)}</span><strong>${value ? 'Ready' : 'Needs attention'}</strong></li>`).join('') : '';
      const readinessCard = readiness ? `<article class="record-card" data-settings-readiness><div><span class="record-id">LAUNCH READINESS</span><h3>${readiness.ok ? 'Ready for configured traffic' : 'Configuration needs attention'}</h3><p>The gate reports configuration health without exposing secrets. External provider and deployment setup must still be verified for the launch environment.</p><ul style="display:grid;gap:6px;margin:12px 0 0;padding:0;list-style:none">${readinessChecks}</ul></div></article>` : '';
      list.innerHTML = `<div class="report-period">Authenticated tenant configuration · secrets are never displayed</div><article class="report-card"><div><span class="record-id">WORKSPACE</span><h3>${escapeHtml(workspace.businessName || 'Configured workspace')}</h3><p>${escapeHtml(workspace.serviceLabel || 'Service operations')} · ${escapeHtml(workspace.timeZone || 'Timezone configured server-side')}</p></div></article>${readinessCard}<article class="record-card"><div><span class="record-id">DATA PORTABILITY</span><h3>Owner migration snapshot</h3><p>Download a tenant-scoped JSON snapshot for backup or managed-storage migration. Sensitive control fields are removed.</p><div class="record-actions"><button class="ghost-btn" type="button" data-settings-snapshot>Download snapshot</button><button class="ghost-btn" type="button" data-settings-validate-snapshot>Validate snapshot</button><button class="ghost-btn" type="button" data-settings-import-snapshot>Import snapshot</button><input type="file" accept="application/json,.json" hidden data-settings-snapshot-input /><input type="file" accept="application/json,.json" hidden data-settings-import-snapshot-input /></div><p data-settings-import-status class="muted"></p></div></article><article class="record-card"><div><span class="record-id">LANDING PAGE HANDOFF</span><h3>Connected service: ${escapeHtml(serviceKey || 'current tenant')}</h3><p>Booking <code>${escapeHtml(origin)}/booking.html?service=${encodeURIComponent(serviceKey)}</code> · Owner portal <code>${escapeHtml(origin)}/portal?service=${encodeURIComponent(serviceKey)}</code></p></div></article><article class="record-card"><div><span class="record-id">PUBLIC INTEGRATION</span><h3>Versioned tenant manifest</h3><p><code>/api/public/tenant?service=${encodeURIComponent(serviceKey)}</code> · availability, catalog, leads, bookings, and owner handoff are tenant-scoped.</p></div></article>${checks}`;
      list.insertAdjacentHTML('beforeend', '<article class="record-card"><div><span class="record-id">LEAD PIPELINE</span><h3>Customize lead stages</h3><p>Use the stages that match this service business. Existing leads prevent removal of a stage until they are moved.</p><div class="record-actions"><input type="text" data-settings-lead-stages placeholder="New, Contacted, Qualified" aria-label="Lead stages, comma separated" /><button class="ghost-btn" type="button" data-settings-save-lead-stages>Save stages</button></div><p data-settings-lead-stages-status class="muted"></p></div></article>');
      list.insertAdjacentHTML('beforeend', '<article class="record-card"><div><span class="record-id">LANDING PAGE CONFIGURATION</span><h3>Owner-editable service profile</h3><p>These values flow to the connected landing page manifest and booking experience.</p><div class="record-actions" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px"><input type="text" data-settings-business-name placeholder="Business name" aria-label="Business name" /><input type="text" data-settings-service-label placeholder="Service label" aria-label="Service label" /><input type="text" data-settings-time-zone placeholder="America/New_York" aria-label="Time zone" /><input type="number" min="30" max="480" data-settings-appointment-minutes placeholder="Appointment minutes" aria-label="Appointment minutes" /><button class="ghost-btn" type="button" data-settings-save-workspace>Save service profile</button></div><p data-settings-workspace-status class="muted"></p></div></article>');
      const workspaceBusinessName = list.querySelector('[data-settings-business-name]');
      const workspaceServiceLabel = list.querySelector('[data-settings-service-label]');
      const workspaceTimeZone = list.querySelector('[data-settings-time-zone]');
      const workspaceAppointmentMinutes = list.querySelector('[data-settings-appointment-minutes]');
      const workspaceSave = list.querySelector('[data-settings-save-workspace]');
      const workspaceStatus = list.querySelector('[data-settings-workspace-status]');
      workspaceBusinessName.value = workspace.businessName || '';
      workspaceServiceLabel.value = workspace.serviceLabel || '';
      workspaceTimeZone.value = workspace.timeZone || '';
      workspaceAppointmentMinutes.value = workspace.appointmentMinutes || 60;
      if (repository.session?.owner?.role === 'owner') workspaceSave?.addEventListener('click', async () => { workspaceSave.disabled = true; workspaceStatus.textContent = 'Saving…'; try { const result = await repository.updateWorkspaceSettings({ businessName: workspaceBusinessName.value.trim(), serviceLabel: workspaceServiceLabel.value.trim(), timeZone: workspaceTimeZone.value.trim(), appointmentMinutes: Number(workspaceAppointmentMinutes.value) }); workspace = result.workspace || workspace; workspaceStatus.textContent = 'Service profile saved. Connected landing pages will use the updated values.'; } catch (error) { workspaceStatus.textContent = error.message === 'invalid_workspace_configuration' ? 'Check the business name, time zone, and appointment length.' : 'Could not save service profile.'; } finally { workspaceSave.disabled = false; } }); else { [workspaceBusinessName, workspaceServiceLabel, workspaceTimeZone, workspaceAppointmentMinutes].forEach((input) => { input.disabled = true; }); workspaceSave.remove(); workspaceStatus.textContent = 'Only owners can change landing page configuration.'; }
      list.insertAdjacentHTML('beforeend', '<article class="record-card"><div><span class="record-id">LANDING PAGE KEYS</span><h3>Attach another service page</h3><p>Claim a unique service key for a future plumbing, electrical, washing, or other landing page. The page can discover the same tenant manifest without a deployment edit.</p><div class="record-actions"><input type="text" data-settings-service-key placeholder="e.g. commercial-plumbing" aria-label="New landing page service key" /><button class="ghost-btn" type="button" data-settings-claim-service-key>Claim key</button></div><p data-settings-service-key-status class="muted"></p><p data-settings-service-key-list class="muted"></p></div></article>');
      list.insertAdjacentHTML('beforeend', '<article class="record-card"><div><span class="record-id">PUBLIC CONTACT</span><h3>Landing-page contact and coverage</h3><p>These values are safe public marketing metadata; never enter credentials here.</p><div class="record-actions" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px"><input type="tel" data-settings-contact-phone placeholder="(843) 555-0100" aria-label="Public contact phone" /><input type="email" data-settings-contact-email placeholder="hello@example.com" aria-label="Public contact email" /><input type="text" data-settings-service-area placeholder="Charleston area" aria-label="Service area" /><button class="ghost-btn" type="button" data-settings-save-contact>Save public contact</button></div><p data-settings-contact-status class="muted"></p></div></article>');
      const contactPhoneInput = list.querySelector('[data-settings-contact-phone]');
      const contactEmailInput = list.querySelector('[data-settings-contact-email]');
      const serviceAreaInput = list.querySelector('[data-settings-service-area]');
      const contactSave = list.querySelector('[data-settings-save-contact]');
      const contactStatus = list.querySelector('[data-settings-contact-status]');
      contactPhoneInput.value = workspace.contactPhone || '';
      contactEmailInput.value = workspace.contactEmail || '';
      serviceAreaInput.value = workspace.serviceArea || '';
      if (repository.session?.owner?.role === 'owner') contactSave?.addEventListener('click', async () => { contactSave.disabled = true; contactStatus.textContent = 'Saving…'; try { const result = await repository.updateWorkspaceSettings({ contactPhone: contactPhoneInput.value.trim(), contactEmail: contactEmailInput.value.trim(), serviceArea: serviceAreaInput.value.trim() }); workspace = result.workspace || workspace; contactStatus.textContent = 'Public contact metadata saved.'; } catch (error) { contactStatus.textContent = error.message === 'invalid_contact_phone' ? 'Enter a valid phone number.' : error.message === 'invalid_contact_email' ? 'Enter a valid email address.' : 'Could not save public contact metadata.'; } finally { contactSave.disabled = false; } }); else { [contactPhoneInput, contactEmailInput, serviceAreaInput].forEach((input) => { input.disabled = true; }); contactSave.remove(); contactStatus.textContent = 'Only owners can change public contact metadata.'; }
      const serviceKeyInput = list.querySelector('[data-settings-service-key]');
      const serviceKeyButton = list.querySelector('[data-settings-claim-service-key]');
      const serviceKeyStatus = list.querySelector('[data-settings-service-key-status]');
      const serviceKeyList = list.querySelector('[data-settings-service-key-list]');
      try { const keys = await repository.getLandingPageKeys(); serviceKeyList.textContent = `Connected keys: ${(keys.serviceKeys || []).join(', ') || 'none'}`; } catch { serviceKeyList.textContent = 'Landing page key configuration unavailable.'; }
      if (repository.session?.owner?.role === 'owner') serviceKeyButton?.addEventListener('click', async () => { serviceKeyButton.disabled = true; serviceKeyStatus.textContent = 'Claiming…'; try { const result = await repository.claimLandingPageKey(serviceKeyInput.value.trim()); serviceKeyList.textContent = `Connected keys: ${(result.serviceKeys || []).join(', ')}`; serviceKeyStatus.textContent = `Claimed ${result.service}.`; serviceKeyInput.value = ''; } catch (error) { serviceKeyStatus.textContent = error.message === 'service_key_already_claimed' ? 'That key is already claimed by another tenant.' : 'Use 2–80 lowercase letters, numbers, or hyphens.'; } finally { serviceKeyButton.disabled = false; } }); else { serviceKeyInput.disabled = true; serviceKeyButton.remove(); serviceKeyStatus.textContent = 'Only owners can attach landing pages.'; }
      const stageInput = list.querySelector('[data-settings-lead-stages]');
      const stageSave = list.querySelector('[data-settings-save-lead-stages]');
      const stageStatus = list.querySelector('[data-settings-lead-stages-status]');
      try { const leadStageResult = await repository.getLeadStages(); stageInput.value = (leadStageResult.stages || []).filter((stage) => stage !== 'Converted').join(', '); } catch { stageStatus.textContent = 'Lead stage configuration unavailable.'; stageSave.disabled = true; }
      if (repository.session?.owner?.role === 'owner') stageSave?.addEventListener('click', async () => { const stages = stageInput.value.split(',').map((stage) => stage.trim()).filter(Boolean); stageSave.disabled = true; stageStatus.textContent = 'Saving…'; try { const result = await repository.updateLeadStages(stages); stageInput.value = (result.stages || []).filter((stage) => stage !== 'Converted').join(', '); stageStatus.textContent = 'Lead stages saved.'; } catch (error) { stageStatus.textContent = error.message === 'existing_leads_use_removed_stage' ? 'Move existing leads out of a stage before removing it.' : 'Could not save lead stages.'; } finally { stageSave.disabled = false; } }); else { stageInput.disabled = true; stageSave.remove(); stageStatus.textContent = 'Only owners can change pipeline stages.'; }
      const snapshotButton = list.querySelector('[data-settings-snapshot]');
      const validateButton = list.querySelector('[data-settings-validate-snapshot]');
      const snapshotInput = list.querySelector('[data-settings-snapshot-input]');
      const importButton = list.querySelector('[data-settings-import-snapshot]');
      const importInput = list.querySelector('[data-settings-import-snapshot-input]');
      const importStatus = list.querySelector('[data-settings-import-status]');
      if (repository.session?.owner?.role === 'owner') {
        snapshotButton?.addEventListener('click', async () => { snapshotButton.disabled = true; try { await repository.exportRecords('tenant-snapshot'); } catch { snapshotButton.disabled = false; return; } snapshotButton.textContent = 'Snapshot downloaded'; });
        validateButton?.addEventListener('click', () => snapshotInput?.click());
        snapshotInput?.addEventListener('change', async () => { const file = snapshotInput.files?.[0]; if (!file) return; validateButton.disabled = true; validateButton.textContent = 'Validating…'; try { const result = await repository.validateTenantSnapshot(JSON.parse(await file.text())); validateButton.textContent = result.valid ? 'Snapshot is valid' : `${result.errors.length} validation issue${result.errors.length === 1 ? '' : 's'}`; } catch { validateButton.textContent = 'Could not validate'; } finally { validateButton.disabled = false; snapshotInput.value = ''; } });
        importButton?.addEventListener('click', () => importInput?.click());
        importInput?.addEventListener('change', async () => { const file = importInput.files?.[0]; if (!file) return; importButton.disabled = true; importButton.textContent = 'Validating…'; importStatus.textContent = ''; try { const snapshot = JSON.parse(await file.text()); const validation = await repository.validateTenantSnapshot(snapshot); if (!validation.valid) { importButton.textContent = `${validation.errors.length} validation issue${validation.errors.length === 1 ? '' : 's'}`; importStatus.textContent = validation.errors.slice(0, 3).join(' · '); return; } if (!window.confirm(`Import ${Object.values(validation.counts || {}).reduce((total, count) => total + Number(count || 0), 0)} records into ${workspace.businessName || 'this workspace'}? Existing collections included in the snapshot will be replaced.`)) { importButton.textContent = 'Import snapshot'; return; } await repository.importTenantSnapshot(snapshot, crypto.randomUUID()); importButton.textContent = 'Snapshot imported'; importStatus.textContent = 'Reload the workspace to view restored records.'; } catch { importButton.textContent = 'Import failed'; importStatus.textContent = 'Choose a valid tenant snapshot and try again.'; } finally { importButton.disabled = false; importInput.value = ''; } });
      } else { snapshotButton?.remove(); validateButton?.remove(); importButton?.remove(); snapshotInput?.remove(); importInput?.remove(); importStatus?.remove(); }
    } catch {
      list.innerHTML = '<div class="empty-state">Workspace settings are unavailable. Check the authenticated session and integration configuration.</div>';
    }
  };
  link.addEventListener('click', openSettings);
})();
