import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { createHmac } from 'node:crypto';

const port = 4377;
const base = `http://127.0.0.1:${port}`;
const tempDir = mkdtempSync(join(tmpdir(), 'northstar-smoke-'));
const dataFile = join(tempDir, 'state.json');
const webhookSecret = 'smoke-webhook-secret';
const messageWebhookSecret = 'smoke-message-webhook-secret';
const ownerEmail = 'owner@example.test';
const ownerPassword = 'smoke-owner-password';
const ownerDigest = createHmac('sha256', 'northstar-local-demo-secret-change-me').update(ownerPassword).digest('hex');
const serverEnv = { ...process.env, PORT: String(port), NORTHSTAR_DATA_FILE: dataFile, NORTHSTAR_PAYMENT_WEBHOOK_SECRET: webhookSecret, NORTHSTAR_MESSAGE_WEBHOOK_SECRET: messageWebhookSecret, NORTHSTAR_ALLOWED_ORIGINS: 'https://plumbing.example', NORTHSTAR_OWNER_EMAIL: ownerEmail, NORTHSTAR_OWNER_PASSWORD_DIGEST: ownerDigest };
const server = spawn(process.execPath, ['server.mjs'], { cwd: new URL('.', import.meta.url), env: serverEnv, stdio: 'ignore' });
let restartedServer;
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const request = async (path, options = {}) => { const response = await fetch(`${base}${path}`, options); const body = await response.json().catch(() => ({})); return { response, body }; };
const jsonOptions = (method, body, token) => ({ method, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(body) });
try {
  for (let attempt = 0; attempt < 40; attempt += 1) { try { if ((await fetch(`${base}/api/health`)).ok) break; } catch {} await new Promise((resolve) => setTimeout(resolve, 50)); if (attempt === 39) throw new Error('server did not start'); }
  const portal = await fetch(`${base}/portal?service=plumbing`);
  const bookingPage = await fetch(`${base}/booking.html?service=plumbing`);
  assert(portal.status === 200 && (await portal.text()).includes('northstar') && bookingPage.status === 200 && (await bookingPage.text()).includes('NORTHSTAR ONLINE BOOKING'), 'portal or booking landing handoff failed');
  const malformed = await fetch(`${base}/api/public/leads`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{' });
  const oversized = await fetch(`${base}/api/public/leads`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'x'.repeat(70_000) }) });
  const availability = await request('/api/public/availability?service=plumbing');
  const tenantConfig = await request('/api/public/tenant?service=plumbing');
  const unknownTenantConfig = await request('/api/public/tenant?service=not-a-service');
  const secureLogin = await request('/api/auth/login?service=plumbing', jsonOptions('POST', { email: ownerEmail, password: ownerPassword }));
  const secureSession = await request('/api/session', { headers: { authorization: `Bearer ${secureLogin.body.token}` } });
  const invalidLogin = await request('/api/auth/login?service=plumbing', jsonOptions('POST', { email: ownerEmail, password: 'wrong-password' }));
  const loginBurst = await Promise.all(Array.from({ length: 8 }, () => request('/api/auth/login?service=plumbing', jsonOptions('POST', { email: ownerEmail, password: 'wrong-password' }))));
  const booking = await request('/api/public/bookings?service=plumbing', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-booking-1' }, body: JSON.stringify({ name: 'Booked Customer', phone: '843-555-0111', requestedService: 'Emergency leak repair', time: 'Tomorrow 10:30 AM', source: 'Clearwater Plumbing landing page', website: '' }) });
  const duplicateBooking = await request('/api/public/bookings?service=plumbing', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-booking-1' }, body: JSON.stringify({ name: 'Booked Customer', phone: '843-555-0111', requestedService: 'Emergency leak repair', time: 'Tomorrow 10:30 AM', source: 'Clearwater Plumbing landing page' }) });
  const repeatCustomerBooking = await request('/api/public/bookings?service=plumbing', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-booking-2' }, body: JSON.stringify({ name: 'Booked Customer', phone: '843-555-0111', requestedService: 'Annual plumbing maintenance', time: 'Tomorrow 1:00 PM', source: 'Clearwater Plumbing landing page' }) });
  const bookedCustomerRecords = await request('/api/customers?search=Booked%20Customer', { headers: { authorization: `Bearer ${secureLogin.body.token}` } });
  const availabilityAfterBooking = await request('/api/public/availability?service=plumbing');
  const cors = await fetch(`${base}/api/public/leads`, { method: 'OPTIONS', headers: { origin: 'https://plumbing.example' } });
  const blockedCors = await fetch(`${base}/api/public/leads`, { method: 'OPTIONS', headers: { origin: 'https://untrusted.example' } });
  assert(malformed.status === 400 && oversized.status === 400 && availability.response.ok && availability.body.slots.includes('Tomorrow 10:30 AM') && tenantConfig.response.status === 200 && tenantConfig.body.tenant.slug === 'clearwater-plumbing' && tenantConfig.body.bookingPath.includes('service=plumbing') && unknownTenantConfig.response.status === 404 && unknownTenantConfig.body.error === 'unknown_service' && secureLogin.response.status === 200 && secureLogin.body.owner.role === 'owner' && secureSession.response.ok && secureSession.body.owner.id === 'owner_configured' && secureSession.body.owner.name === 'Workspace owner' && secureSession.body.tenant.slug === 'clearwater-plumbing' && invalidLogin.response.status === 401 && loginBurst.some((result) => result.response.status === 429) && booking.response.status === 201 && booking.body.booked === true && duplicateBooking.response.status === 200 && duplicateBooking.body.duplicate === true && repeatCustomerBooking.response.status === 201 && bookedCustomerRecords.body.items.length === 1 && bookedCustomerRecords.body.items[0].name === 'Booked Customer' && availabilityAfterBooking.response.ok && !availabilityAfterBooking.body.slots.includes('Tomorrow 10:30 AM') && !availabilityAfterBooking.body.slots.includes('Tomorrow 1:00 PM') && cors.status === 204 && cors.headers.get('access-control-allow-origin') === 'https://plumbing.example' && blockedCors.status === 403, 'auth, tenant config, malformed input protection, or online booking failed');
  const publicLead = await request('/api/public/leads', jsonOptions('POST', { service: 'plumbing', name: 'Smoke Lead', phone: '843-555-0100', idempotencyKey: 'smoke-lead-1' }));
  const duplicateLead = await request('/api/public/leads', jsonOptions('POST', { service: 'plumbing', name: 'Smoke Lead', phone: '843-555-0100', idempotencyKey: 'smoke-lead-1' }));
  const qualifiedLead = await request(`/api/leads/${publicLead.body.id}/status`, jsonOptions('POST', { status: 'Qualified', note: 'Confirmed scope and service window.' }, secureLogin.body.token));
  const qualifiedLeadRecords = await request('/api/leads?search=Smoke%20Lead', { headers: { authorization: `Bearer ${secureLogin.body.token}` } });
  assert(publicLead.response.status === 201 && publicLead.body.tenant.slug === 'clearwater-plumbing' && duplicateLead.response.status === 200 && duplicateLead.body.duplicate === true && duplicateLead.body.id === publicLead.body.id && qualifiedLead.response.status === 200 && qualifiedLead.body.lead.status === 'Qualified' && qualifiedLeadRecords.body.items.find((item) => item.id === publicLead.body.id)?.status === 'Qualified', 'public lead intake failed');
  const login = await request('/api/auth/demo-login?service=plumbing', jsonOptions('POST', {}));
  assert(login.response.ok, 'demo login failed');
  const token = login.body.token;
  const newTeamMember = await request('/api/team', jsonOptions('POST', { name: 'Jordan Lee', role: 'Apprentice' }, token));
  const teamRoster = await request('/api/team', { headers: { authorization: `Bearer ${token}` } });
  const duplicateTeamMember = await request('/api/team', jsonOptions('POST', { name: 'Jordan Lee', role: 'Field technician' }, token));
  assert(newTeamMember.response.status === 201 && newTeamMember.body.name === 'Jordan Lee' && teamRoster.body.items.some((item) => item.name === 'Jordan Lee' && item.status === 'Available') && duplicateTeamMember.response.status === 409, 'team roster management failed');
  const createdCustomer = await request('/api/customers', jsonOptions('POST', { name: 'Direct Job Customer', phone: '843-555-0122' }, token));
  const specialist = await request('/api/team', jsonOptions('POST', { name: 'Electrical Specialist', role: 'Field technician', skills: ['Electrical'] }, token));
  const skillsJob = await request('/api/jobs', jsonOptions('POST', { customerId: createdCustomer.body.id, service: 'Panel inspection', requiredSkill: 'Plumbing', time: 'Next Tuesday 3:00 PM' }, token));
  const unqualifiedAssignment = await request(`/api/jobs/${skillsJob.body.id}/assign`, jsonOptions('POST', { technician: specialist.body.name }, token));
  assert(specialist.response.status === 201 && specialist.body.skills.includes('Electrical') && unqualifiedAssignment.response.status === 422 && unqualifiedAssignment.body.error === 'technician_missing_required_skill', 'technician skill enforcement failed');
  const directJob = await request('/api/jobs', jsonOptions('POST', { customerId: createdCustomer.body.id, service: 'Scheduled repair', time: 'Tomorrow 8:00 AM' }, token));
  const firstVisit = await request(`/api/jobs/${directJob.body.id}/visits`, jsonOptions('POST', { time: 'Tomorrow 2:00 PM', technician: 'Alex Rivera' }, token));
  const listedVisits = await request(`/api/jobs/${directJob.body.id}/visits`, { headers: { authorization: `Bearer ${token}` } });
  const visitStarted = await request(`/api/jobs/${directJob.body.id}/visits/${firstVisit.body.id}/status`, jsonOptions('POST', { status: 'En route' }, token));
  const visitInProgress = await request(`/api/jobs/${directJob.body.id}/visits/${firstVisit.body.id}/status`, jsonOptions('POST', { status: 'In progress' }, token));
  const visitCompleted = await request(`/api/jobs/${directJob.body.id}/visits/${firstVisit.body.id}/status`, jsonOptions('POST', { status: 'Completed' }, token));
  const duplicateVisit = await request(`/api/jobs/${directJob.body.id}/visits`, jsonOptions('POST', { time: 'Tomorrow 2:00 PM', technician: 'Alex Rivera' }, token));
  const conflictingDirectJob = await request('/api/jobs', jsonOptions('POST', { customerId: createdCustomer.body.id, service: 'Second repair', time: 'Tomorrow 8:00 AM' }, token));
  const missingCustomerJob = await request('/api/jobs', jsonOptions('POST', { customerId: 'missing-customer', time: 'Tomorrow 1:00 PM' }, token));
  const invalidDirectStatus = await request(`/api/jobs/${directJob.body.id}/status`, jsonOptions('POST', { status: 'In progress' }, token));
  const canceledDirectJob = await request(`/api/jobs/${directJob.body.id}/status`, jsonOptions('POST', { status: 'Canceled' }, token));
  const rebookedDirectJob = await request('/api/jobs', jsonOptions('POST', { customerId: createdCustomer.body.id, service: 'Replacement repair', time: 'Tomorrow 8:00 AM' }, token));
  assert(createdCustomer.response.status === 201 && directJob.response.status === 201 && firstVisit.response.status === 201 && listedVisits.body.visits.length === 1 && visitStarted.body.status === 'En route' && visitInProgress.body.status === 'In progress' && visitCompleted.body.status === 'Completed' && duplicateVisit.response.status === 409 && conflictingDirectJob.response.status === 409 && conflictingDirectJob.body.error === 'appointment_time_unavailable' && missingCustomerJob.response.status === 404 && invalidDirectStatus.response.status === 409 && invalidDirectStatus.body.error === 'invalid_job_transition' && canceledDirectJob.body.status === 'Canceled' && rebookedDirectJob.response.status === 201, 'direct job scheduling conflict protection failed');
  const technicianLogin = await request('/api/auth/demo-login?service=plumbing&role=technician', jsonOptions('POST', {}));
  const technicianSession = await request('/api/session', { headers: { authorization: `Bearer ${technicianLogin.body.token}` } });
  const technicianReports = await request('/api/reports/overview', { headers: { authorization: `Bearer ${technicianLogin.body.token}` } });
  const technicianJobCreate = await request('/api/jobs', jsonOptions('POST', { customerId: 'not-allowed', time: 'tomorrow' }, technicianLogin.body.token));
  const accountantLogin = await request('/api/auth/demo-login?service=plumbing&role=accountant', jsonOptions('POST', {}));
  const accountantReports = await request('/api/reports/overview', { headers: { authorization: `Bearer ${accountantLogin.body.token}` } });
  assert(technicianLogin.response.ok && technicianSession.body.owner.role === 'technician' && technicianSession.body.permissions.includes('field:write') && !technicianSession.body.permissions.includes('jobs:write') && technicianReports.response.status === 403 && technicianJobCreate.response.status === 403 && accountantReports.response.ok, 'role permissions failed');
  const catalogItem = await request('/api/catalog', jsonOptions('POST', { name: 'Emergency pipe repair', description: 'Priority diagnosis and repair for active leaks', priceFrom: '$389' }, token));
  const catalog = await request('/api/catalog?search=Emergency%20pipe', { headers: { authorization: `Bearer ${token}` } });
  const accountantCatalogItem = await request('/api/catalog', jsonOptions('POST', { name: 'Unauthorized pricebook item', description: 'Should not be created', priceFrom: '$1' }, accountantLogin.body.token));
  const pricebookEstimate = await request('/api/estimates', jsonOptions('POST', { customer: 'Pricebook Customer', service: 'Ignored service label', amount: 389, catalogItemId: catalogItem.body.id }, token));
  const optionEstimate = await request('/api/estimates', jsonOptions('POST', { customer: 'Options Customer', service: 'Panel upgrade', options: [{ label: 'Good', description: 'Repair existing panel', amount: 450 }, { label: 'Better', description: 'Repair and add surge protection', amount: 650 }, { label: 'Best', description: 'Replace panel and add surge protection', amount: 950 }] }, token));
  const optionEstimateView = await request(`/api/public/estimate?token=${encodeURIComponent(optionEstimate.body.estimateApprovalToken)}`);
  const selectedOptionApproval = await request(`/api/public/estimate/approve?token=${encodeURIComponent(optionEstimate.body.estimateApprovalToken)}`, jsonOptions('POST', { optionId: 'OPTION-2', approverName: 'Options Customer' }));
  const invalidPricebookEstimate = await request('/api/estimates', jsonOptions('POST', { customer: 'Pricebook Customer', amount: 389, catalogItemId: 'other-tenant-catalog-item' }, token));
  assert(catalogItem.response.status === 201 && catalog.body.items.some((item) => item.id === catalogItem.body.id) && accountantCatalogItem.response.status === 403 && pricebookEstimate.response.status === 201 && pricebookEstimate.body.service === 'Emergency pipe repair' && pricebookEstimate.body.pricebookItem === 'Emergency pipe repair' && optionEstimate.response.status === 201 && optionEstimateView.body.options.length === 3 && selectedOptionApproval.body.selectedOptionId === 'OPTION-2' && selectedOptionApproval.body.value === '$650.00' && invalidPricebookEstimate.response.status === 404, 'pricebook or estimate options workflow failed');
  const material = await request('/api/materials', jsonOptions('POST', { name: '1/2 inch copper coupling', sku: 'CU-COUP-12', unit: 'each', unitCost: 8.5, onHand: 4, reorderPoint: 1 }, token));
  const materials = await request('/api/materials?search=copper', { headers: { authorization: `Bearer ${token}` } });
  assert(material.response.status === 201 && materials.body.items[0].status === 'In stock' && materials.body.items[0].onHand === 4, 'inventory receipt failed');
  const message = await request('/api/messages', jsonOptions('POST', { customer: 'Smoke Lead', channel: 'SMS', message: 'Your technician is scheduled for tomorrow at 9:00 AM.' }, token));
  const messages = await request('/api/messages?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const messageEventBody = JSON.stringify({ tenantId: 'clearwater-plumbing', eventId: 'msg-event-1', messageId: message.body.id, status: 'sent', providerReference: 'SMS-42' });
  const messageDelivery = await request('/api/webhooks/messages', { method: 'POST', headers: { 'content-type': 'application/json', 'x-northstar-signature': createHmac('sha256', messageWebhookSecret).update(messageEventBody).digest('hex') }, body: messageEventBody });
  const messageDeliveryDuplicate = await request('/api/webhooks/messages', { method: 'POST', headers: { 'content-type': 'application/json', 'x-northstar-signature': createHmac('sha256', messageWebhookSecret).update(messageEventBody).digest('hex') }, body: messageEventBody });
  assert(message.response.status === 201 && message.body.status === 'Queued (provider pending)' && messages.body.items.length === 1 && messages.body.items[0].channel === 'SMS' && messageDelivery.response.status === 200 && messageDelivery.body.message.status === 'Sent' && messageDeliveryDuplicate.response.status === 200 && messageDeliveryDuplicate.body.duplicate === true, 'message workflow failed');
  const leadList = await request('/api/leads?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const leadNotifications = await request('/api/notifications?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const audit = await request('/api/audit?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const notificationRead = await request(`/api/notifications/${leadNotifications.body.items[0].id}/read`, jsonOptions('POST', {}, token));
  const readNotifications = await request('/api/notifications?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  assert(leadList.body.items.length === 1 && leadNotifications.body.items.length === 1 && audit.body.items.length >= 1 && audit.body.items[0].entityType === 'customer' && leadNotifications.body.items[0].title === 'New lead needs follow-up' && notificationRead.body.read === true && readNotifications.body.items[0].read === true, 'owner cannot see captured lead or audit trail');
  const converted = await request(`/api/leads/${leadList.body.items[0].id}/convert`, jsonOptions('POST', { time: 'Tomorrow 9:00 AM' }, token));
  const inboundMessageBody = JSON.stringify({ tenantId: 'clearwater-plumbing', eventId: 'msg-inbound-1', from: '843-555-0100', channel: 'SMS', message: 'Can you confirm the arrival window?', jobId: converted.body.job.id });
  const inboundMessage = await request('/api/webhooks/messages/inbound', { method: 'POST', headers: { 'content-type': 'application/json', 'x-northstar-signature': createHmac('sha256', messageWebhookSecret).update(inboundMessageBody).digest('hex') }, body: inboundMessageBody });
  const inboundMessageDuplicate = await request('/api/webhooks/messages/inbound', { method: 'POST', headers: { 'content-type': 'application/json', 'x-northstar-signature': createHmac('sha256', messageWebhookSecret).update(inboundMessageBody).digest('hex') }, body: inboundMessageBody });
  assert(inboundMessage.response.status === 201 && inboundMessage.body.message.direction === 'inbound' && inboundMessage.body.message.customer === 'Smoke Lead' && inboundMessage.body.message.jobId === converted.body.job.id && inboundMessageDuplicate.response.status === 200 && inboundMessageDuplicate.body.duplicate === true, 'inbound message workflow failed');
  const recommendations = await request(`/api/dispatch/recommendations?jobId=${encodeURIComponent(converted.body.job.id)}`, { headers: { authorization: `Bearer ${token}` } });
  assert(recommendations.response.ok && recommendations.body.recommendations.length >= 3 && recommendations.body.recommendations.some((item) => item.available), 'dispatch recommendation failed');
  const materialUse = await request(`/api/jobs/${converted.body.job.id}/materials`, jsonOptions('POST', { materialId: material.body.id, quantity: 3 }, token));
  const labor = await request(`/api/jobs/${converted.body.job.id}/labor`, jsonOptions('POST', { technician: 'Alex Rivera', hours: 2, hourlyRate: 75 }, token));
  const jobCosts = await request('/api/job-costs', { headers: { authorization: `Bearer ${token}` } });
  const lowStockMaterials = await request('/api/materials?search=copper', { headers: { authorization: `Bearer ${token}` } });
  const purchaseOrder = await request('/api/purchase-orders', jsonOptions('POST', { materialId: material.body.id, vendor: 'Charleston Supply', quantity: 6, unitCost: 7.75 }, token));
  const openPurchaseOrders = await request('/api/purchase-orders', { headers: { authorization: `Bearer ${token}` } });
  const receivedPurchaseOrder = await request(`/api/purchase-orders/${purchaseOrder.body.id}/receive`, jsonOptions('POST', {}, token));
  const convertedCustomer = await request('/api/customers?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const publicStatus = await request(`/api/public/job-status?token=${encodeURIComponent(converted.body.customerPortalToken)}`);
  assert(converted.response.status === 201 && materialUse.response.ok && materialUse.body.job.materials[0].quantity === 3 && labor.response.status === 201 && labor.body.jobCost.laborCost === '$150.00' && jobCosts.body.items.some((item) => item.jobId === converted.body.job.id && item.totalCost === '$175.50' && item.grossMargin === '$-175.50') && lowStockMaterials.body.items[0].onHand === 1 && lowStockMaterials.body.items[0].status === 'Low stock' && purchaseOrder.response.status === 201 && openPurchaseOrders.body.items[0].status === 'Open' && receivedPurchaseOrder.response.ok && receivedPurchaseOrder.body.material.onHand === 7 && converted.body.job.leadId === leadList.body.items[0].id && converted.body.job.customerId === converted.body.customer.id && convertedCustomer.body.items.length === 1 && publicStatus.body.status === 'Unassigned', 'lead conversion, inventory, or job costing failed');
  const assigned = await request(`/api/jobs/${converted.body.job.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const appointmentReminder = await request(`/api/jobs/${converted.body.job.id}/remind`, jsonOptions('POST', { channel: 'SMS' }, token));
  const duplicateAppointmentReminder = await request(`/api/jobs/${converted.body.job.id}/remind`, jsonOptions('POST', { channel: 'SMS' }, token));
  const jobNotification = await request(`/api/jobs/${converted.body.job.id}/notify`, jsonOptions('POST', { template: 'en_route', channel: 'SMS' }, token));
  const jobMessages = await request('/api/messages?search=Alex%20Rivera', { headers: { authorization: `Bearer ${token}` } });
  const assignmentTimeline = await request('/api/activities?search=Assigned%20Plumbing', { headers: { authorization: `Bearer ${token}` } });
  const teamBusy = await request('/api/team', { headers: { authorization: `Bearer ${token}` } });
  const completed = await request(`/api/jobs/${converted.body.job.id}/complete`, jsonOptions('POST', { note: 'Repaired leak and reviewed shutoff procedure.' }, token));
  const completedStatus = await request(`/api/public/job-status?token=${encodeURIComponent(converted.body.customerPortalToken)}`);
  const completedTimeline = await request('/api/activities?search=Repaired%20leak', { headers: { authorization: `Bearer ${token}` } });
  const automatedMessages = await request('/api/messages?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  assert(assigned.body.status === 'Confirmed' && appointmentReminder.response.status === 201 && appointmentReminder.body.message.template === 'appointment_reminder' && duplicateAppointmentReminder.response.status === 200 && duplicateAppointmentReminder.body.duplicate === true && jobNotification.response.status === 201 && jobNotification.body.template === 'en_route' && jobNotification.body.status === 'Queued (provider pending)' && jobMessages.body.items.some((item) => item.jobId === converted.body.job.id) && automatedMessages.body.items.some((item) => item.jobId === converted.body.job.id && item.template === 'confirmation') && automatedMessages.body.items.some((item) => item.jobId === converted.body.job.id && item.template === 'completed') && assignmentTimeline.body.items.length === 1 && teamBusy.body.items.find((item) => item.name === 'Alex Rivera')?.status === 'On job' && teamBusy.body.items.find((item) => item.name === 'Alex Rivera')?.activeJobs === 1 && completed.response.status === 200 && completed.body.status === 'Completed' && completed.body.completedAt && completedStatus.body.status === 'Completed' && completedTimeline.body.items.length === 1, 'job completion or notification workflow failed');
  const asset = await request('/api/assets', jsonOptions('POST', { customer: 'Smoke Lead', name: 'Tankless water heater', serial: 'TS-42', installed: '2026-09-04', warrantyThrough: '2029-09-04' }, token));
  const assets = await request('/api/assets?search=TS-42', { headers: { authorization: `Bearer ${token}` } });
  const assetExport = await fetch(`${base}/api/export?type=assets`, { headers: { authorization: `Bearer ${token}` } });
  const assetAudit = await request('/api/audit?search=asset.created', { headers: { authorization: `Bearer ${token}` } });
  assert(asset.response.status === 201 && asset.body.warrantyThrough === '2029-09-04' && assets.body.items.length === 1 && assets.body.items[0].customer === 'Smoke Lead' && (await assetExport.text()).includes('TS-42') && assetAudit.body.items.some((item) => item.action === 'asset.created'), 'customer asset workflow failed');
  const profile = await request(`/api/customers/${encodeURIComponent(converted.body.customer.id)}`, { headers: { authorization: `Bearer ${token}` } });
  assert(profile.response.ok && profile.body.customer?.name === 'Smoke Lead' && profile.body.jobs?.length >= 1 && profile.body.assets?.length === 1 && profile.body.activities?.length >= 1, 'customer profile aggregation failed');
  const location = await request(`/api/customers/${encodeURIComponent(converted.body.customer.id)}/locations`, jsonOptions('POST', { label: 'Second property', address: '200 Meeting St, Charleston' }, token));
  assert(location.response.status === 201 && location.body.label === 'Second property', 'multi-location workflow failed');
  const plan = await request('/api/plans', jsonOptions('POST', { customer: 'Smoke Lead', service: 'Annual plumbing maintenance', amount: 89, renewal: 'Sep 2027' }, token));
  const renewedPlan = await request(`/api/plans/${plan.body.id}/renew`, jsonOptions('POST', { time: 'Next month 9:00 AM' }, token));
  const pausedPlan = await request(`/api/plans/${plan.body.id}/pause`, jsonOptions('POST', { note: 'Customer requested a seasonal pause.' }, token));
  const resumedPlan = await request(`/api/plans/${plan.body.id}/resume`, jsonOptions('POST', {}, token));
  const canceledPlan = await request(`/api/plans/${plan.body.id}/cancel`, jsonOptions('POST', { note: 'Customer moved out of service area.' }, token));
  assert(plan.response.status === 201 && renewedPlan.body.plan.status === 'Active' && renewedPlan.body.nextJob.service === 'Annual plumbing maintenance' && renewedPlan.body.nextJob.planId === plan.body.id && pausedPlan.body.plan.status === 'Paused' && resumedPlan.body.plan.status === 'Active' && canceledPlan.body.plan.status === 'Canceled', 'recurring plan workflow failed');
  const fieldJob = await request('/api/jobs', jsonOptions('POST', { customerId: converted.body.customer.id, service: 'Follow-up inspection', time: 'Friday 2:00 PM' }, token));
  await request(`/api/jobs/${fieldJob.body.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const technicianVisit = await request(`/api/jobs/${fieldJob.body.id}/visits`, jsonOptions('POST', { time: 'Friday 4:00 PM', technician: 'Alex Rivera' }, token));
  const techLink = await request(`/api/jobs/${fieldJob.body.id}/technician-link`, jsonOptions('POST', {}, token));
  const techUrl = new URL(techLink.body.url, base);
  const techView = await request(`/api/public/technician-job${techUrl.search}`);
  const techVisitEnRoute = await request(`/api/public/technician-job/visit-status${techUrl.search}`, jsonOptions('POST', { visitId: technicianVisit.body.id, status: 'En route' }));
  const techVisitInProgress = await request(`/api/public/technician-job/visit-status${techUrl.search}`, jsonOptions('POST', { visitId: technicianVisit.body.id, status: 'In progress' }));
  const techVisitCompleted = await request(`/api/public/technician-job/visit-status${techUrl.search}`, jsonOptions('POST', { visitId: technicianVisit.body.id, status: 'Completed' }));
  const techPhoto = await request(`/api/public/technician-job/photo${techUrl.search}`, jsonOptions('POST', { photoUrl: 'https://cdn.example.test/jobs/field-42.jpg', caption: 'Repaired coupling before reassembly.' }));
  const techViewWithPhoto = await request(`/api/public/technician-job${techUrl.search}`);
  const techLabor = await request(`/api/public/technician-job/labor${techUrl.search}`, jsonOptions('POST', { hours: 1.5 }));
  const techMaterial = await request(`/api/public/technician-job/materials${techUrl.search}`, jsonOptions('POST', { materialId: material.body.id, quantity: 2 }));
  const techViewWithUsage = await request(`/api/public/technician-job${techUrl.search}`);
  const techEnRoute = await request(`/api/public/technician-job/status${techUrl.search}`, jsonOptions('POST', { status: 'En route' }));
  const techStarted = await request(`/api/public/technician-job/status${techUrl.search}`, jsonOptions('POST', { status: 'In progress' }));
  const checklistBeforeComplete = await request(`/api/public/technician-job${techUrl.search}`);
  const techIncomplete = await request(`/api/public/technician-job/complete${techUrl.search}`, jsonOptions('POST', { note: 'Attempted early completion.' }));
  for (let index = 0; index < checklistBeforeComplete.body.checklist.length; index += 1) await request(`/api/public/technician-job/checklist${techUrl.search}`, jsonOptions('POST', { index, completed: true }));
  const techComplete = await request(`/api/public/technician-job/complete${techUrl.search}`, jsonOptions('POST', { note: 'Inspected fittings and documented follow-up recommendations.' }));
  assert(technicianVisit.response.status === 201 && techLink.response.ok && techView.body.technician === 'Alex Rivera' && techView.body.visits.length === 1 && techVisitEnRoute.body.status === 'En route' && techVisitInProgress.body.status === 'In progress' && techVisitCompleted.body.status === 'Completed' && techPhoto.response.status === 201 && techViewWithPhoto.body.photos.length === 1 && techViewWithPhoto.body.photos[0].caption.includes('coupling') && techLabor.response.status === 201 && techLabor.body.entry.hours === 1.5 && techMaterial.response.status === 200 && techMaterial.body.material.onHand === 5 && techViewWithUsage.body.materials.find((item) => item.id === material.body.id)?.onHand === 5 && checklistBeforeComplete.body.checklist.length === 3 && techEnRoute.body.status === 'En route' && techStarted.body.status === 'In progress' && techIncomplete.response.status === 409 && techIncomplete.body.error === 'checklist_incomplete' && techComplete.body.status === 'Completed', 'technician mobile workflow failed');
  const reviewLink = await request(`/api/jobs/${fieldJob.body.id}/review-link`, jsonOptions('POST', {}, token));
  const reviewUrl = new URL(reviewLink.body.url, base);
  const reviewView = await request(`/api/public/review${reviewUrl.search}`);
  const review = await request(`/api/public/review${reviewUrl.search}`, jsonOptions('POST', { rating: 5, comment: 'Clear communication and careful work.' }));
  const reviewDuplicate = await request(`/api/public/review${reviewUrl.search}`, jsonOptions('POST', { rating: 5 }));
  const dashboardAfterReview = await request('/api/dashboard', { headers: { authorization: `Bearer ${token}` } });
  const reportAfterReview = await request('/api/reports/overview', { headers: { authorization: `Bearer ${token}` } });
  const reviewRecords = await request('/api/reviews?search=Smoke Lead', { headers: { authorization: `Bearer ${token}` } });
  const reviewExportResponse = await fetch(`${base}/api/export?type=reviews`, { headers: { authorization: `Bearer ${token}` } });
  const reviewExportCsv = await reviewExportResponse.text();
  assert(reviewLink.response.ok && reviewView.body.submitted === false && review.response.status === 201 && review.body.rating === 5 && reviewDuplicate.response.status === 409 && reviewRecords.body.items.some((item) => item.comment.includes('Clear communication')) && reviewExportResponse.ok && reviewExportCsv.includes('Clear communication'), 'review workflow failed');
  const customerLink = await request(`/api/jobs/${fieldJob.body.id}/customer-link`, jsonOptions('POST', {}, token));
  const customerUrl = new URL(customerLink.body.url, base);
  const customerPortal = await request(`/api/public/customer-portal${customerUrl.search}`);
  assert(customerPortal.body.jobs.some((item) => item.id === fieldJob.body.id && item.photos?.[0]?.caption.includes('coupling')), 'customer portal field evidence visibility failed');
  assert(customerPortal.body.assets?.[0]?.warrantyThrough === '2029-09-04', 'customer portal warranty visibility failed');
  const portalConfirm = await request(`/api/public/customer-portal/confirm${customerUrl.search}`, jsonOptions('POST', { jobId: customerPortal.body.jobs[0].id }));
  const portalConfirmDuplicate = await request(`/api/public/customer-portal/confirm${customerUrl.search}`, jsonOptions('POST', { jobId: customerPortal.body.jobs[0].id }));
  const portalEstimate = await request('/api/estimates', jsonOptions('POST', { customer: 'Smoke Lead', service: 'Follow-up estimate', amount: 275 }, token));
  const customerPortalWithEstimate = await request(`/api/public/customer-portal${customerUrl.search}`);
  const portalApproval = await request(`/api/public/estimate/approve?token=${encodeURIComponent(customerPortalWithEstimate.body.estimates.find((item) => item.id === portalEstimate.body.id).estimateApprovalToken)}`, jsonOptions('POST', { approverName: 'Smoke Lead' }));
  const portalInvoice = await request('/api/invoices', jsonOptions('POST', { estimateId: portalEstimate.body.id }, token));
  const portalSchedule = await request(`/api/invoices/${portalInvoice.body.id}/schedule`, jsonOptions('POST', { installments: [{ amount: 100, due: 'At booking' }, { amount: 175, due: 'On completion' }] }, token));
  const portalScheduleView = await request(`/api/invoices/${portalInvoice.body.id}/schedule`, { headers: { authorization: `Bearer ${token}` } });
  const customerPortalWithInvoice = await request(`/api/public/customer-portal${customerUrl.search}`);
  const portalInvoiceView = customerPortalWithInvoice.body.invoices.find((item) => item.id === portalInvoice.body.id);
  const portalPaymentIntent = await request(`/api/public/customer-portal/payment-intent${customerUrl.search}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-customer-portal-payment' }, body: JSON.stringify({ invoiceId: portalInvoiceView.id, amount: 75, method: 'ACH' }) });
  const portalWebhookBody = JSON.stringify({ tenantId: 'clearwater-plumbing', eventId: 'evt-portal-1', intentId: portalPaymentIntent.body.id, status: 'succeeded', reference: 'PROVIDER-42' });
  const portalWebhook = await request('/api/webhooks/payments', { method: 'POST', headers: { 'content-type': 'application/json', 'x-northstar-signature': createHmac('sha256', webhookSecret).update(portalWebhookBody).digest('hex') }, body: portalWebhookBody });
  const portalWebhookDuplicate = await request('/api/webhooks/payments', { method: 'POST', headers: { 'content-type': 'application/json', 'x-northstar-signature': createHmac('sha256', webhookSecret).update(portalWebhookBody).digest('hex') }, body: portalWebhookBody });
  const customerPortalAfterPayment = await request(`/api/public/customer-portal${customerUrl.search}`);
  const estimateJob = await request(`/api/estimates/${portalEstimate.body.id}/convert`, jsonOptions('POST', { time: 'Next Thursday 11:00 AM' }, token));
  const estimateJobAssigned = await request(`/api/jobs/${estimateJob.body.job.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const estimateTechLink = await request(`/api/jobs/${estimateJob.body.job.id}/technician-link`, jsonOptions('POST', {}, token));
  const estimateTechUrl = new URL(estimateTechLink.body.url, base);
  const technicianPaymentIntent = await request(`/api/public/technician-job/payment-intent${estimateTechUrl.search}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-technician-payment' }, body: JSON.stringify({ amount: 50, method: 'Card' }) });
  const technicianPaymentDuplicate = await request(`/api/public/technician-job/payment-intent${estimateTechUrl.search}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-technician-payment' }, body: JSON.stringify({ amount: 50, method: 'Card' }) });
  const customerRequest = await request(`/api/public/customer-portal/request${customerUrl.search}`, jsonOptions('POST', { type: 'Question', message: 'Can you confirm the next service window?' }));
  const openRequests = await request('/api/requests?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const requestNotifications = await request('/api/notifications?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const resolvedRequest = await request(`/api/requests/${customerRequest.body.id}/resolve`, jsonOptions('POST', { note: 'Sent the customer the confirmed service window.' }, token));
  const customerPortalToken = new URL(customerLink.body.url, base).searchParams.get('token');
  assert(technicianVisit.response.status === 201 && customerPortal.body.jobs.some((item) => item.id === fieldJob.body.id && item.visits?.length === 1 && item.visits[0].technician === 'Alex Rivera'), 'customer portal visit visibility failed');
  const cancellationRequest = await request('/api/public/customer-portal/request?token=' + encodeURIComponent(customerPortalToken), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ type: 'Cancellation request', message: 'Please cancel the next visit.' }) });
  assert(cancellationRequest.response.status === 201 && cancellationRequest.body.status === 'Open', 'customer cancellation request workflow failed');
  const jobCancellationRequest = await request('/api/public/customer-portal/request?token=' + encodeURIComponent(customerPortalToken), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ type: 'Cancellation request', jobId: customerPortal.body.jobs[0].id, message: 'Please cancel this appointment.' }) });
  assert(jobCancellationRequest.response.status === 201 && jobCancellationRequest.body.status === 'Open', 'job-specific cancellation request workflow failed');
  assert(customerLink.response.ok && customerPortal.body.customer.name === 'Smoke Lead' && customerPortal.body.locations.length === 2 && customerPortal.body.locations.some((item) => item.address.includes('200 Meeting')) && customerPortal.body.jobs.length >= 2 && portalConfirm.body.status === 'Confirmed' && portalConfirmDuplicate.body.duplicate === true && customerPortal.body.assets.length === 1 && !customerPortal.body.customer.tenantId && customerPortalWithEstimate.body.estimates.some((item) => item.id === portalEstimate.body.id && item.estimateApprovalToken) && portalApproval.body.status === 'Accepted' && portalInvoice.response.status === 201 && portalSchedule.response.status === 201 && portalScheduleView.body.items.length === 2 && portalInvoiceView.balance === 275 && portalInvoiceView.schedule.length === 2 && !Object.prototype.hasOwnProperty.call(portalInvoiceView.schedule[0], 'tenantId') && !Object.prototype.hasOwnProperty.call(portalInvoiceView.schedule[0], 'invoiceId') && portalPaymentIntent.response.status === 201 && portalPaymentIntent.body.status === 'Pending provider' && portalWebhook.response.ok && portalWebhook.body.invoice.balance === 200 && portalWebhook.body.intent.status === 'Succeeded' && portalWebhookDuplicate.response.status === 200 && portalWebhookDuplicate.body.duplicate === true && customerPortalAfterPayment.body.invoices.find((item) => item.id === portalInvoice.body.id).schedule[0].paidAmount === 75 && estimateJob.response.status === 201 && estimateJobAssigned.body.status === 'Confirmed' && estimateTechLink.response.ok && technicianPaymentIntent.response.status === 201 && technicianPaymentIntent.body.source === 'technician_field' && technicianPaymentDuplicate.response.status === 200 && technicianPaymentDuplicate.body.duplicate === true && estimateJob.body.job.estimateId === portalEstimate.body.id && estimateJob.body.job.checklist.length === 3 && customerRequest.response.status === 201 && openRequests.body.items.length === 1 && requestNotifications.body.items.some((item) => item.title === 'Customer request needs response') && resolvedRequest.body.status === 'Resolved', 'customer portal or field payment workflow failed');
  const guardJob = await request('/api/jobs', jsonOptions('POST', { customerId: converted.body.customer.id, service: 'Capacity check', time: 'Next Monday 10:00 AM' }, token));
  await request(`/api/jobs/${guardJob.body.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const conflictJob = await request('/api/jobs', jsonOptions('POST', { customerId: converted.body.customer.id, service: 'Same-time service', time: 'Next Monday 11:00 AM' }, token));
  const conflictAssign = await request(`/api/jobs/${conflictJob.body.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const conflictReschedule = await request(`/api/jobs/${conflictJob.body.id}/reschedule`, jsonOptions('POST', { time: 'Next Monday 10:00 AM' }, token));
  assert(conflictAssign.response.status === 200 && conflictReschedule.response.status === 409 && conflictReschedule.body.error === 'technician_schedule_conflict', 'technician conflict protection failed');
  const reschedule = await request(`/api/jobs/${directJob.body.id}/reschedule`, jsonOptions('POST', { time: 'Tomorrow 9:30 AM' }, token));
  assert(reschedule.response.status === 200 && reschedule.body.notification?.template === 'rescheduled', 'reschedule notification workflow failed');
  const estimate = await request('/api/estimates', jsonOptions('POST', { customer: 'Smoke Customer', service: 'Leak repair', amount: 425 }, token));
  const estimateReminder = await request(`/api/estimates/${estimate.body.id}/remind`, jsonOptions('POST', { channel: 'SMS' }, token));
  const duplicateEstimateReminder = await request(`/api/estimates/${estimate.body.id}/remind`, jsonOptions('POST', { channel: 'SMS' }, token));
  const publicEstimate = await request(`/api/public/estimate?token=${encodeURIComponent(estimate.body.estimateApprovalToken)}`);
  const approved = await request(`/api/public/estimate/approve?token=${encodeURIComponent(estimate.body.estimateApprovalToken)}`, jsonOptions('POST', { approverName: 'Smoke Customer' }));
  const invoice = await request('/api/invoices', jsonOptions('POST', { estimateId: estimate.body.id }, token));
  const invoiceLink = await request(`/api/invoices/${invoice.body.id}/payment-link`, jsonOptions('POST', {}, token));
  const invoiceUrl = new URL(invoiceLink.body.url, base);
  const publicInvoice = await request(`/api/public/invoice${invoiceUrl.search}`);
  const paymentIntent = await request(`/api/public/invoice/payment-intent${invoiceUrl.search}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-payment-intent' }, body: JSON.stringify({ amount: 50, method: 'Card' }) });
  const duplicatePaymentIntent = await request(`/api/public/invoice/payment-intent${invoiceUrl.search}`, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'smoke-payment-intent' }, body: JSON.stringify({ amount: 50, method: 'Card' }) });
  const partial = await request(`/api/invoices/${invoice.body.id}/pay`, jsonOptions('POST', { amount: 100, method: 'Card', reference: 'SMOKE-1' }, token));
  const invoiceReminder = await request(`/api/invoices/${invoice.body.id}/remind`, jsonOptions('POST', { channel: 'SMS' }, token));
  const duplicateInvoiceReminder = await request(`/api/invoices/${invoice.body.id}/remind`, jsonOptions('POST', { channel: 'SMS' }, token));
  const paid = await request(`/api/invoices/${invoice.body.id}/pay`, jsonOptions('POST', { method: 'ACH' }, token));
  const paymentLedger = await request('/api/payments?search=Smoke%20Customer', { headers: { authorization: `Bearer ${token}` } });
  const timeline = await request('/api/activities?search=Smoke%20Customer', { headers: { authorization: `Bearer ${token}` } });
  assert(estimate.response.status === 201 && estimateReminder.response.status === 201 && estimateReminder.body.message.template === 'estimate_reminder' && duplicateEstimateReminder.response.status === 200 && duplicateEstimateReminder.body.duplicate === true && publicEstimate.body.status === 'Draft' && approved.body.status === 'Accepted' && invoice.response.status === 201 && invoiceLink.response.ok && publicInvoice.body.customer === 'Smoke Customer' && publicInvoice.body.balance === 425 && paymentIntent.response.status === 201 && paymentIntent.body.status === 'Pending provider' && duplicatePaymentIntent.response.status === 200 && duplicatePaymentIntent.body.duplicate === true && partial.body.invoice.status === 'Partially paid' && partial.body.payment.amount === 100 && invoiceReminder.response.status === 201 && invoiceReminder.body.message.template === 'invoice_reminder' && duplicateInvoiceReminder.response.status === 200 && duplicateInvoiceReminder.body.duplicate === true && paid.body.invoice.status === 'Paid' && paid.body.invoice.balance === 0 && paymentLedger.body.items.length === 2 && timeline.body.items.length >= 2, 'quote-to-cash flow failed');
  const exportResponse = await fetch(`${base}/api/export?type=invoices`, { headers: { authorization: `Bearer ${token}` } });
  const exportCsv = await exportResponse.text();
  assert(exportResponse.ok && exportResponse.headers.get('content-type').startsWith('text/csv') && exportCsv.includes('Smoke Customer') && exportCsv.includes('Paid'), 'CSV export failed');
  const otherLogin = await request('/api/auth/demo-login?service=powerwashing', jsonOptions('POST', {}));
  const otherLeads = await request('/api/leads?search=Smoke%20Lead', { headers: { authorization: `Bearer ${otherLogin.body.token}` } });
  assert(otherLeads.body.items.length === 0, 'tenant isolation failed');
  const logout = await request('/api/auth/logout', jsonOptions('POST', {}, token));
  const revoked = await request('/api/session', { headers: { authorization: `Bearer ${token}` } });
  assert(logout.response.ok && revoked.response.status === 401, 'logout revocation failed');
  server.kill(); await new Promise((resolve) => setTimeout(resolve, 100));
  restartedServer = spawn(process.execPath, ['server.mjs'], { cwd: new URL('.', import.meta.url), env: serverEnv, stdio: 'ignore' });
  for (let attempt = 0; attempt < 40; attempt += 1) { try { if ((await fetch(`${base}/api/health`)).ok) break; } catch {} await new Promise((resolve) => setTimeout(resolve, 50)); if (attempt === 39) throw new Error('server did not restart'); }
  const revokedAfterRestart = await request('/api/session', { headers: { authorization: `Bearer ${token}` } });
  assert(revokedAfterRestart.response.status === 401, 'logout revocation did not survive restart');
  console.log('Northstar smoke test passed: intake, conversion, quote-to-cash, signed payment webhook, isolation, logout, restart revocation');
} finally { server.kill(); restartedServer?.kill(); rmSync(tempDir, { recursive: true, force: true }); }
