import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';

const port = 4377;
const base = `http://127.0.0.1:${port}`;
const tempDir = mkdtempSync(join(tmpdir(), 'northstar-smoke-'));
const dataFile = join(tempDir, 'state.json');
const server = spawn(process.execPath, ['server.mjs'], { cwd: new URL('.', import.meta.url), env: { ...process.env, PORT: String(port), NORTHSTAR_DATA_FILE: dataFile, NORTHSTAR_ALLOWED_ORIGINS: 'https://plumbing.example' }, stdio: 'ignore' });
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const request = async (path, options = {}) => { const response = await fetch(`${base}${path}`, options); const body = await response.json().catch(() => ({})); return { response, body }; };
const jsonOptions = (method, body, token) => ({ method, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(body) });
try {
  for (let attempt = 0; attempt < 40; attempt += 1) { try { if ((await fetch(`${base}/api/health`)).ok) break; } catch {} await new Promise((resolve) => setTimeout(resolve, 50)); if (attempt === 39) throw new Error('server did not start'); }
  const malformed = await fetch(`${base}/api/public/leads`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{' });
  const oversized = await fetch(`${base}/api/public/leads`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'x'.repeat(70_000) }) });
  const cors = await fetch(`${base}/api/public/leads`, { method: 'OPTIONS', headers: { origin: 'https://plumbing.example' } });
  const blockedCors = await fetch(`${base}/api/public/leads`, { method: 'OPTIONS', headers: { origin: 'https://untrusted.example' } });
  assert(malformed.status === 400 && oversized.status === 400 && cors.status === 204 && cors.headers.get('access-control-allow-origin') === 'https://plumbing.example' && blockedCors.status === 403, 'malformed input protection failed');
  const publicLead = await request('/api/public/leads', jsonOptions('POST', { service: 'plumbing', name: 'Smoke Lead', phone: '843-555-0100', idempotencyKey: 'smoke-lead-1' }));
  const duplicateLead = await request('/api/public/leads', jsonOptions('POST', { service: 'plumbing', name: 'Smoke Lead', phone: '843-555-0100', idempotencyKey: 'smoke-lead-1' }));
  assert(publicLead.response.status === 201 && publicLead.body.tenant.slug === 'clearwater-plumbing' && duplicateLead.response.status === 200 && duplicateLead.body.duplicate === true && duplicateLead.body.id === publicLead.body.id, 'public lead intake failed');
  const login = await request('/api/auth/demo-login?service=plumbing', jsonOptions('POST', {}));
  assert(login.response.ok, 'demo login failed');
  const token = login.body.token;
  const leadList = await request('/api/leads?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const leadNotifications = await request('/api/notifications?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const notificationRead = await request(`/api/notifications/${leadNotifications.body.items[0].id}/read`, jsonOptions('POST', {}, token));
  const readNotifications = await request('/api/notifications?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  assert(leadList.body.items.length === 1 && leadNotifications.body.items.length === 1 && leadNotifications.body.items[0].title === 'New lead needs follow-up' && notificationRead.body.read === true && readNotifications.body.items[0].read === true, 'owner cannot see captured lead');
  const converted = await request(`/api/leads/${leadList.body.items[0].id}/convert`, jsonOptions('POST', { time: 'Tomorrow 9:00 AM' }, token));
  const convertedCustomer = await request('/api/customers?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const publicStatus = await request(`/api/public/job-status?token=${encodeURIComponent(converted.body.customerPortalToken)}`);
  assert(converted.response.status === 201 && converted.body.job.leadId === leadList.body.items[0].id && converted.body.job.customerId === converted.body.customer.id && convertedCustomer.body.items.length === 1 && publicStatus.body.status === 'Unassigned', 'lead conversion failed');
  const assigned = await request(`/api/jobs/${converted.body.job.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const assignmentTimeline = await request('/api/activities?search=Assigned%20Plumbing', { headers: { authorization: `Bearer ${token}` } });
  const teamBusy = await request('/api/team', { headers: { authorization: `Bearer ${token}` } });
  const completed = await request(`/api/jobs/${converted.body.job.id}/complete`, jsonOptions('POST', { note: 'Repaired leak and reviewed shutoff procedure.' }, token));
  const completedStatus = await request(`/api/public/job-status?token=${encodeURIComponent(converted.body.customerPortalToken)}`);
  const completedTimeline = await request('/api/activities?search=Repaired%20leak', { headers: { authorization: `Bearer ${token}` } });
  assert(assigned.body.status === 'Confirmed' && assignmentTimeline.body.items.length === 1 && teamBusy.body.items.find((item) => item.name === 'Alex Rivera')?.status === 'On job' && teamBusy.body.items.find((item) => item.name === 'Alex Rivera')?.activeJobs === 1 && completed.response.status === 200 && completed.body.status === 'Completed' && completed.body.completedAt && completedStatus.body.status === 'Completed' && completedTimeline.body.items.length === 1, 'job completion workflow failed');
  const asset = await request('/api/assets', jsonOptions('POST', { customer: 'Smoke Lead', name: 'Tankless water heater', serial: 'TS-42', installed: '2026-09-04' }, token));
  const assets = await request('/api/assets?search=TS-42', { headers: { authorization: `Bearer ${token}` } });
  const assetExport = await fetch(`${base}/api/export?type=assets`, { headers: { authorization: `Bearer ${token}` } });
  assert(asset.response.status === 201 && assets.body.items.length === 1 && assets.body.items[0].customer === 'Smoke Lead' && (await assetExport.text()).includes('TS-42'), 'customer asset workflow failed');
  const profile = await request(`/api/customers/${encodeURIComponent(converted.body.customer.id)}`, { headers: { authorization: `Bearer ${token}` } });
  assert(profile.response.ok && profile.body.customer?.name === 'Smoke Lead' && profile.body.jobs?.length >= 1 && profile.body.assets?.length === 1 && profile.body.activities?.length >= 1, 'customer profile aggregation failed');
  const location = await request(`/api/customers/${encodeURIComponent(converted.body.customer.id)}/locations`, jsonOptions('POST', { label: 'Second property', address: '200 Meeting St, Charleston' }, token));
  assert(location.response.status === 201 && location.body.label === 'Second property', 'multi-location workflow failed');
  const plan = await request('/api/plans', jsonOptions('POST', { customer: 'Smoke Lead', service: 'Annual plumbing maintenance', amount: 89, renewal: 'Sep 2027' }, token));
  const renewedPlan = await request(`/api/plans/${plan.body.id}/renew`, jsonOptions('POST', { time: 'Next month 9:00 AM' }, token));
  assert(plan.response.status === 201 && renewedPlan.body.plan.status === 'Active' && renewedPlan.body.nextJob.service === 'Annual plumbing maintenance' && renewedPlan.body.nextJob.planId === plan.body.id, 'recurring plan workflow failed');
  const fieldJob = await request('/api/jobs', jsonOptions('POST', { customerId: converted.body.customer.id, service: 'Follow-up inspection', time: 'Friday 2:00 PM' }, token));
  await request(`/api/jobs/${fieldJob.body.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const techLink = await request(`/api/jobs/${fieldJob.body.id}/technician-link`, jsonOptions('POST', {}, token));
  const techUrl = new URL(techLink.body.url, base);
  const techView = await request(`/api/public/technician-job${techUrl.search}`);
  const techEnRoute = await request(`/api/public/technician-job/status${techUrl.search}`, jsonOptions('POST', { status: 'En route' }));
  const techStarted = await request(`/api/public/technician-job/status${techUrl.search}`, jsonOptions('POST', { status: 'In progress' }));
  const checklistBeforeComplete = await request(`/api/public/technician-job${techUrl.search}`);
  const techIncomplete = await request(`/api/public/technician-job/complete${techUrl.search}`, jsonOptions('POST', { note: 'Attempted early completion.' }));
  for (let index = 0; index < checklistBeforeComplete.body.checklist.length; index += 1) await request(`/api/public/technician-job/checklist${techUrl.search}`, jsonOptions('POST', { index, completed: true }));
  const techComplete = await request(`/api/public/technician-job/complete${techUrl.search}`, jsonOptions('POST', { note: 'Inspected fittings and documented follow-up recommendations.' }));
  assert(techLink.response.ok && techView.body.technician === 'Alex Rivera' && checklistBeforeComplete.body.checklist.length === 3 && techEnRoute.body.status === 'En route' && techStarted.body.status === 'In progress' && techIncomplete.response.status === 409 && techIncomplete.body.error === 'checklist_incomplete' && techComplete.body.status === 'Completed', 'technician mobile workflow failed');
  const reviewLink = await request(`/api/jobs/${fieldJob.body.id}/review-link`, jsonOptions('POST', {}, token));
  const reviewUrl = new URL(reviewLink.body.url, base);
  const reviewView = await request(`/api/public/review${reviewUrl.search}`);
  const review = await request(`/api/public/review${reviewUrl.search}`, jsonOptions('POST', { rating: 5, comment: 'Clear communication and careful work.' }));
  const reviewDuplicate = await request(`/api/public/review${reviewUrl.search}`, jsonOptions('POST', { rating: 5 }));
  const dashboardAfterReview = await request('/api/dashboard', { headers: { authorization: `Bearer ${token}` } });
  const reportAfterReview = await request('/api/reports/overview', { headers: { authorization: `Bearer ${token}` } });
  const reviewRecords = await request('/api/reviews?search=Smoke Lead', { headers: { authorization: `Bearer ${token}` } });
  const reviewExportResponse = await fetch(`${base}/api/export?type=reviews`, { headers: { authorization: `Bearer ${token}` } });
  const reviewExportCsv = await reviewExportResponse.text();
  assert(reviewLink.response.ok && reviewView.body.submitted === false && review.response.status === 201 && review.body.rating === 5 && reviewDuplicate.response.status === 409 && reviewRecords.body.items.some((item) => item.comment.includes('Clear communication')) && reviewExportResponse.ok && reviewExportCsv.includes('Clear communication'), 'review workflow failed');
  const customerLink = await request(`/api/jobs/${fieldJob.body.id}/customer-link`, jsonOptions('POST', {}, token));
  const customerUrl = new URL(customerLink.body.url, base);
  const customerPortal = await request(`/api/public/customer-portal${customerUrl.search}`);
  const portalEstimate = await request('/api/estimates', jsonOptions('POST', { customer: 'Smoke Lead', service: 'Follow-up estimate', amount: 275 }, token));
  const customerPortalWithEstimate = await request(`/api/public/customer-portal${customerUrl.search}`);
  const portalApproval = await request(`/api/public/estimate/approve?token=${encodeURIComponent(customerPortalWithEstimate.body.estimates.find((item) => item.id === portalEstimate.body.id).estimateApprovalToken)}`, jsonOptions('POST', {}));
  const estimateJob = await request(`/api/estimates/${portalEstimate.body.id}/convert`, jsonOptions('POST', { time: 'Next Thursday 11:00 AM' }, token));
  const customerRequest = await request(`/api/public/customer-portal/request${customerUrl.search}`, jsonOptions('POST', { type: 'Question', message: 'Can you confirm the next service window?' }));
  const openRequests = await request('/api/requests?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const requestNotifications = await request('/api/notifications?search=Smoke%20Lead', { headers: { authorization: `Bearer ${token}` } });
  const resolvedRequest = await request(`/api/requests/${customerRequest.body.id}/resolve`, jsonOptions('POST', { note: 'Sent the customer the confirmed service window.' }, token));
  assert(customerLink.response.ok && customerPortal.body.customer.name === 'Smoke Lead' && customerPortal.body.locations.length === 2 && customerPortal.body.locations.some((item) => item.address.includes('200 Meeting')) && customerPortal.body.jobs.length >= 2 && customerPortal.body.assets.length === 1 && !customerPortal.body.customer.tenantId && customerPortalWithEstimate.body.estimates.some((item) => item.id === portalEstimate.body.id && item.estimateApprovalToken) && portalApproval.body.status === 'Accepted' && estimateJob.response.status === 201 && estimateJob.body.job.estimateId === portalEstimate.body.id && estimateJob.body.job.checklist.length === 3 && customerRequest.response.status === 201 && openRequests.body.items.length === 1 && requestNotifications.body.items.some((item) => item.title === 'Customer request needs response') && resolvedRequest.body.status === 'Resolved', 'customer portal workflow failed');
  const guardJob = await request('/api/jobs', jsonOptions('POST', { customerId: converted.body.customer.id, service: 'Capacity check', time: 'Next Monday 10:00 AM' }, token));
  await request(`/api/jobs/${guardJob.body.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  const conflictJob = await request('/api/jobs', jsonOptions('POST', { customerId: converted.body.customer.id, service: 'Same-time service', time: 'Next Monday 10:00 AM' }, token));
  const conflictAssign = await request(`/api/jobs/${conflictJob.body.id}/assign`, jsonOptions('POST', { technician: 'Alex Rivera' }, token));
  assert(conflictAssign.response.status === 409 && conflictAssign.body.error === 'technician_schedule_conflict', 'technician conflict protection failed');
  const estimate = await request('/api/estimates', jsonOptions('POST', { customer: 'Smoke Customer', service: 'Leak repair', amount: 425 }, token));
  const publicEstimate = await request(`/api/public/estimate?token=${encodeURIComponent(estimate.body.estimateApprovalToken)}`);
  const approved = await request(`/api/public/estimate/approve?token=${encodeURIComponent(estimate.body.estimateApprovalToken)}`, jsonOptions('POST', {}));
  const invoice = await request('/api/invoices', jsonOptions('POST', { estimateId: estimate.body.id }, token));
  const partial = await request(`/api/invoices/${invoice.body.id}/pay`, jsonOptions('POST', { amount: 100, method: 'Card', reference: 'SMOKE-1' }, token));
  const paid = await request(`/api/invoices/${invoice.body.id}/pay`, jsonOptions('POST', { method: 'ACH' }, token));
  const paymentLedger = await request('/api/payments?search=Smoke%20Customer', { headers: { authorization: `Bearer ${token}` } });
  const timeline = await request('/api/activities?search=Smoke%20Customer', { headers: { authorization: `Bearer ${token}` } });
  assert(estimate.response.status === 201 && publicEstimate.body.status === 'Draft' && approved.body.status === 'Accepted' && invoice.response.status === 201 && partial.body.invoice.status === 'Partially paid' && partial.body.payment.amount === 100 && paid.body.invoice.status === 'Paid' && paid.body.invoice.balance === 0 && paymentLedger.body.items.length === 2 && timeline.body.items.length >= 2, 'quote-to-cash flow failed');
  const exportResponse = await fetch(`${base}/api/export?type=invoices`, { headers: { authorization: `Bearer ${token}` } });
  const exportCsv = await exportResponse.text();
  assert(exportResponse.ok && exportResponse.headers.get('content-type').startsWith('text/csv') && exportCsv.includes('Smoke Customer') && exportCsv.includes('Paid'), 'CSV export failed');
  const otherLogin = await request('/api/auth/demo-login?service=powerwashing', jsonOptions('POST', {}));
  const otherLeads = await request('/api/leads?search=Smoke%20Lead', { headers: { authorization: `Bearer ${otherLogin.body.token}` } });
  assert(otherLeads.body.items.length === 0, 'tenant isolation failed');
  const logout = await request('/api/auth/logout', jsonOptions('POST', {}, token));
  const revoked = await request('/api/session', { headers: { authorization: `Bearer ${token}` } });
  assert(logout.response.ok && revoked.response.status === 401, 'logout revocation failed');
  console.log('Northstar smoke test passed: intake, conversion, quote-to-cash, isolation, logout');
} finally { server.kill(); rmSync(tempDir, { recursive: true, force: true }); }
