(() => {
  const repository = window.northstarRepository;
  if (!repository?.createTask || document.querySelector('#task-dialog')) return;
  const dialog = document.createElement('dialog'); dialog.id = 'task-dialog'; dialog.className = 'workflow-dialog';
  dialog.innerHTML = '<button class="dialog-close" type="button" data-close-task aria-label="Close">×</button><div class="dialog-kicker">OWNER WORKFLOW</div><h2 id="task-title">Add owner task</h2><p id="task-help">Capture a follow-up for today’s focus list. Keep the title actionable and use the detail for the next step or customer context.</p><form><label>Task title<input name="title" type="text" maxlength="160" required placeholder="Follow up with customer" /></label><label>Detail <span>(optional)</span><textarea name="detail" rows="4" maxlength="1000" placeholder="Confirm access window and send estimate link"></textarea></label><label>Due date <span>(optional)</span><input name="dueAt" type="date" /></label><div class="workflow-actions"><button class="ghost-btn" type="button" data-close-task>Cancel</button><button class="primary-btn" type="submit">Add task</button></div><p class="form-message" data-task-status role="status" aria-live="polite"></p></form>';
  dialog.setAttribute('aria-labelledby', 'task-title'); dialog.setAttribute('aria-describedby', 'task-help'); document.body.append(dialog);
  const form = dialog.querySelector('form'); const status = form.querySelector('[data-task-status]'); const submit = form.querySelector('[type="submit"]');
  dialog.querySelectorAll('[data-close-task]').forEach((button) => button.addEventListener('click', () => dialog.close()));
  const open = () => { form.reset(); status.textContent = ''; dialog.showModal(); form.elements.title.focus(); };
  form.addEventListener('submit', async (event) => { event.preventDefault(); const title = form.elements.title.value.trim(); const detail = form.elements.detail.value.trim(); const dueAt = form.elements.dueAt.value; if (!title || title.length > 160 || detail.length > 1000 || (dueAt && !/^\d{4}-\d{2}-\d{2}$/.test(dueAt))) { status.textContent = 'Enter a task title and an optional valid due date.'; return; } submit.disabled = true; status.textContent = 'Saving task…'; try { await repository.createTask(title, detail, dueAt ? `${dueAt}T12:00:00.000Z` : ''); dialog.close(); showToast('Task added to today’s focus.'); window.loadLiveFocus?.(); } catch { status.textContent = 'Could not add the task. Confirm your owner session and try again.'; submit.disabled = false; } });
  document.addEventListener('click', (event) => { const button = event.target.closest('.add-task'); if (!button) return; event.preventDefault(); event.stopImmediatePropagation(); open(); }, true);
})();
